#ifndef IMAGE_0_CODE_ADDRESSES
#define IMAGE_0_CODE_ADDRESSES

#define image_0_start_task_initialization_task		(0x18)
#define image_0_initialization_task		(0x18)
#define image_0_start_task_update_fifo_read_1st_wakeup_request		(0xE14)
#define image_0_update_fifo_read_1st_wakeup_request		(0xE14)
#define image_0_start_task_tx_task_1st_wakeup_request		(0x17C)
#define image_0_tx_task_1st_wakeup_request		(0x17C)
#define image_0_tx_task_wakeup_request		(0x17C)
#define image_0_start_task_flush_task_1st_wakeup_request		(0x780)
#define image_0_flush_task_1st_wakeup_request		(0x780)
#define image_0_start_task_budget_allocator_1st_wakeup_request		(0x898)
#define image_0_budget_allocator_1st_wakeup_request		(0x898)
#define image_0_start_task_debug_routine		(0x90)
#define image_0_debug_routine		(0x90)
#define image_0_debug_routine_handler		(0xC)
#define image_0_scheduling_update_status		(0x4D4)
#define image_0_scheduling_action_not_valid		(0x570)
#define image_0_basic_scheduler_update_dwrr		(0x66C)
#define image_0_complex_scheduler_update_dwrr_basic_schedulers		(0x760)
#define image_0_complex_scheduler_update_dwrr_queues		(0x770)
#define image_0_basic_rate_limiter_complex_scheduler		(0xB74)
#define image_0_basic_rate_limiter_basic_scheduler_no_cs		(0xBAC)
#define image_0_basic_rate_limiter_queue_with_cs_bs		(0xBE0)
#define image_0_basic_rate_limiter_queue_with_bs		(0xC34)
#define image_0_complex_rate_limiter_queue_sir		(0xC70)
#define image_0_complex_rate_limiter_queue_pir		(0xCAC)
#define image_0_complex_rate_limiter_basic_scheduler_sir		(0xCE8)
#define image_0_complex_rate_limiter_basic_scheduler_pir		(0xD24)

#endif
