#ifndef IMAGE_2_CODE_ADDRESSES
#define IMAGE_2_CODE_ADDRESSES

#define image_2_start_task_initialization_task		(0x18)
#define image_2_initialization_task		(0x18)
#define image_2_start_task_ghost_reporting_1st_wakeup_request		(0x768)
#define image_2_ghost_reporting_1st_wakeup_request		(0x768)
#define image_2_start_task_cpu_tx_wakeup_request		(0xB00)
#define image_2_cpu_tx_wakeup_request		(0xB00)
#define image_2_start_task_budget_allocator_1st_wakeup_request		(0x1840)
#define image_2_budget_allocator_1st_wakeup_request		(0x1840)
#define image_2_start_task_debug_routine		(0x50)
#define image_2_debug_routine		(0x50)
#define image_2_start_task_cpu_recycle_wakeup_request		(0x1030)
#define image_2_cpu_recycle_wakeup_request		(0x1030)
#define image_2_start_task_interrupt_coalescing_1st_wakeup_request		(0x1184)
#define image_2_interrupt_coalescing_1st_wakeup_request		(0x1184)
#define image_2_start_task_dhd_tx_complete_wakeup_request		(0x13C)
#define image_2_dhd_tx_complete_wakeup_request		(0x13C)
#define image_2_start_task_dhd_rx_complete_wakeup_request		(0x42C)
#define image_2_dhd_rx_complete_wakeup_request		(0x42C)
#define image_2_start_task_flow_ctrl_task_wakeup_request		(0x1210)
#define image_2_flow_ctrl_task_wakeup_request		(0x1210)
#define image_2_start_task_service_queues_update_fifo_read_1st_wakeup_request		(0x1294)
#define image_2_service_queues_update_fifo_read_1st_wakeup_request		(0x1294)
#define image_2_start_task_service_queues_tx_task_wakeup_request		(0x1324)
#define image_2_service_queues_tx_task_wakeup_request		(0x1324)
#define image_2_debug_routine_handler		(0xC)
#define image_2_scheduling_service_queues_update_status		(0x1434)
#define image_2_scheduling_service_queues_action_not_valid		(0x1518)
#define image_2_complex_scheduler_update_dwrr_basic_schedulers		(0x1634)
#define image_2_complex_scheduler_update_dwrr_queues		(0x1644)
#define image_2_complex_rate_limiter_queue_sir		(0x1654)
#define image_2_complex_rate_limiter_queue_pir		(0x1690)
#define image_2_complex_rate_limiter_basic_scheduler_sir		(0x16CC)
#define image_2_complex_rate_limiter_basic_scheduler_pir		(0x1708)
#define image_2_basic_rate_limiter_complex_scheduler		(0x1744)
#define image_2_basic_rate_limiter_basic_scheduler_no_cs		(0x177C)
#define image_2_basic_rate_limiter_queue_with_cs_bs		(0x17B0)
#define image_2_basic_rate_limiter_queue_with_bs		(0x1804)

#endif
