#ifndef IMAGE_1_CODE_ADDRESSES
#define IMAGE_1_CODE_ADDRESSES

#define image_1_start_task_initialization_task		(0x18)
#define image_1_initialization_task		(0x18)
#define image_1_start_task_direct_processing_wakeup_request		(0x2474)
#define image_1_direct_processing_wakeup_request		(0x2474)
#define image_1_start_task_debug_routine		(0x50)
#define image_1_debug_routine		(0x50)
#define image_1_start_task_gpon_control_wakeup_request		(0x24E0)
#define image_1_gpon_control_wakeup_request		(0x24E0)
#define image_1_start_task_cpu_rx_wakeup_request		(0x2168)
#define image_1_cpu_rx_wakeup_request		(0x2168)
#define image_1_start_task_cpu_recycle_wakeup_request		(0x26B4)
#define image_1_cpu_recycle_wakeup_request		(0x26B4)
#define image_1_start_task_interrupt_coalescing_1st_wakeup_request		(0x2808)
#define image_1_interrupt_coalescing_1st_wakeup_request		(0x2808)
#define image_1_start_task_cpu_rx_meter_budget_allocator_1st_wakeup_request		(0x2610)
#define image_1_cpu_rx_meter_budget_allocator_1st_wakeup_request		(0x2610)
#define image_1_start_task_dhd_tx_post_wakeup_request		(0x56C)
#define image_1_dhd_tx_post_wakeup_request		(0x56C)
#define image_1_start_task_dhd_tx_post_update_fifo_wakeup_request		(0x514)
#define image_1_dhd_tx_post_update_fifo_wakeup_request		(0x514)
#define image_1_start_task_dhd_timer_1st_wakeup_request		(0x13C)
#define image_1_dhd_timer_1st_wakeup_request		(0x13C)
#define image_1_start_task_dhd_mcast_wakeup_request		(0x10E4)
#define image_1_dhd_mcast_wakeup_request		(0x10E4)
#define image_1_start_task_dhd_mcast_update_fifo_wakeup_request		(0x10AC)
#define image_1_dhd_mcast_update_fifo_wakeup_request		(0x10AC)
#define image_1_start_task_cpu_rx_copy_wakeup_request		(0x1C0C)
#define image_1_cpu_rx_copy_wakeup_request		(0x1C0C)
#define image_1_start_task_spdsvc_gen_wakeup_request		(0x28E0)
#define image_1_spdsvc_gen_wakeup_request		(0x28E0)
#define image_1_start_task_tx_abs_recycle_wakeup_request		(0x2CC0)
#define image_1_tx_abs_recycle_wakeup_request		(0x2CC0)
#define image_1_debug_routine_handler		(0xC)

#endif
