#ifndef RUNNER_B_CODE_ADDRESSES
#define RUNNER_B_CODE_ADDRESSES

#define runner_b_start_task_initialization_task		(0x14)
#define runner_b_initialization_task		(0x14)
#define runner_b_start_task_timer_scheduler_set		(0x2DE8)
#define runner_b_timer_scheduler_set		(0x2DE8)
#define runner_b_start_task_cpu_rx_wakeup_request		(0x152C)
#define runner_b_cpu_rx_wakeup_request		(0x152C)
#define runner_b_start_task_cpu_tx_wakeup_request		(0x2628)
#define runner_b_cpu_tx_wakeup_request		(0x2628)
#define runner_b_start_task_policer_budget_allocator_1st_wakeup_request		(0x31E4)
#define runner_b_policer_budget_allocator_1st_wakeup_request		(0x31E4)
#define runner_b_start_task_rate_control_budget_allocator_1st_wakeup_request		(0x2508)
#define runner_b_rate_control_budget_allocator_1st_wakeup_request		(0x2508)
#define runner_b_start_task_wan_interworking_enqueue_wakeup_request		(0x208)
#define runner_b_wan_interworking_enqueue_wakeup_request		(0x208)
#define runner_b_start_task_wan_tx_wakeup_request		(0x6EC)
#define runner_b_wan_tx_wakeup_request		(0x6EC)
#define runner_b_start_task_debug_routine		(0x120)
#define runner_b_debug_routine		(0x120)
#define runner_b_start_task_spdsvc_timer_1st_wakeup_request		(0x2D38)
#define runner_b_spdsvc_timer_1st_wakeup_request		(0x2D38)
#define runner_b_start_task_free_skb_index_wakeup_request		(0x2F7C)
#define runner_b_free_skb_index_wakeup_request		(0x2F7C)
#define runner_b_start_task_dhd_tx_post		(0x3340)
#define runner_b_dhd_tx_post		(0x3340)
#define runner_b_ingress_classification_key_src_ip		(0x1064)
#define runner_b_ingress_classification_key_dst_ip		(0x10A8)
#define runner_b_ingress_classification_key_ipv6_flow_label		(0x10EC)
#define runner_b_ingress_classification_key_generic_rule_1		(0x1110)
#define runner_b_ingress_classification_key_generic_rule_2		(0x1118)
#define runner_b_ingress_classification_key_outer_tpid		(0x1184)
#define runner_b_ingress_classification_key_inner_tpid		(0x1190)
#define runner_b_ingress_classification_key_src_port		(0x11AC)
#define runner_b_ingress_classification_key_dst_port		(0x11CC)
#define runner_b_ingress_classification_key_outer_vlan		(0x11EC)
#define runner_b_ingress_classification_key_inner_vlan		(0x1204)
#define runner_b_ingress_classification_key_dst_mac		(0x1220)
#define runner_b_ingress_classification_key_src_mac		(0x1228)
#define runner_b_ingress_classification_key_ether_type		(0x1250)
#define runner_b_ingress_classification_key_ip_protocol		(0x1264)
#define runner_b_ingress_classification_key_dscp		(0x1288)
#define runner_b_ingress_classification_key_ssid		(0x12A4)
#define runner_b_ingress_classification_key_ingress_port		(0x12BC)
#define runner_b_ingress_classification_key_outer_pbits		(0x12CC)
#define runner_b_ingress_classification_key_inner_pbits		(0x12E4)
#define runner_b_ingress_classification_key_number_of_vlans		(0x1300)
#define runner_b_ingress_classification_key_layer3_protocol		(0x1310)
#define runner_b_cpu_rx_meter_budget_allocate		(0x2E68)
#define runner_b_upstream_rate_limiter_budget_allocate		(0x2EB4)
#define runner_b_schedule_free_skb_index		(0x2F60)

#endif
