/*
   Copyright (c) 2015 Broadcom
   All Rights Reserved

    <:label-BRCM:2015:DUAL/GPL:standard
    
    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License, version 2, as published by
    the Free Software Foundation (the "GPL").
    
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
    
    
    A copy of the GPL is available at http://www.broadcom.com/licenses/GPLv2.php, or by
    writing to the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
    Boston, MA 02111-1307, USA.
    
:>
*/



/* This is an automated file. Do not edit its contents. */


#include "rdd.h"
#include "ru_types.h"

#include "rdd_data_structures_auto.h"

/* >>>RDD_BASIC_RATE_LIMITER_TABLE_DS_ADDRESS_ARR */
uint32_t RDD_BASIC_RATE_LIMITER_TABLE_DS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BASIC_RATE_LIMITER_TABLE_DS_ADDRESS_ARR */


/* >>>RDD_COMPLEX_SCHEDULER_TABLE_ADDRESS_ARR */
uint32_t RDD_COMPLEX_SCHEDULER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x800,
	0x1c00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_COMPLEX_SCHEDULER_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0xc00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_REPORTING_QUEUE_ACCUMULATED_TABLE_ADDRESS_ARR */
uint32_t RDD_REPORTING_QUEUE_ACCUMULATED_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0xe80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_REPORTING_QUEUE_ACCUMULATED_TABLE_ADDRESS_ARR */


/* >>>RDD_REPORTING_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_REPORTING_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0xf00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_REPORTING_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_RUNNER_GLOBAL_REGISTERS_INIT_ADDRESS_ARR */
uint32_t RDD_RUNNER_GLOBAL_REGISTERS_INIT_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0xfa0,
	0x2ee0,
	0xaa0,
	0x160,
	0x6a0,
	0x2a0,
};
/* <<<RDD_RUNNER_GLOBAL_REGISTERS_INIT_ADDRESS_ARR */


/* >>>RDD_DS_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0xfc0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1000,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_BASIC_SCHEDULER_TABLE_DS_ADDRESS_ARR */
uint32_t RDD_BASIC_SCHEDULER_TABLE_DS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1600,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BASIC_SCHEDULER_TABLE_DS_ADDRESS_ARR */


/* >>>RDD_RUNNER_PROFILING_TRACE_BUFFER_ADDRESS_ARR */
uint32_t RDD_RUNNER_PROFILING_TRACE_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1800,
	0x3000,
	0x2800,
	0x2800,
	0x2400,
	0x2000,
};
/* <<<RDD_RUNNER_PROFILING_TRACE_BUFFER_ADDRESS_ARR */


/* >>>RDD_NATC_TBL_CFG_ADDRESS_ARR */
uint32_t RDD_NATC_TBL_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1a00,
	0x3500,
	0x2f00,
	0x2300,
	0x3600,
	0xf00,
};
/* <<<RDD_NATC_TBL_CFG_ADDRESS_ARR */


/* >>>RDD_REGISTERS_BUFFER_ADDRESS_ARR */
uint32_t RDD_REGISTERS_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1a48,
	0x36c8,
	0x2680,
	0x2700,
	0x2b80,
	0xb80,
};
/* <<<RDD_REGISTERS_BUFFER_ADDRESS_ARR */


/* >>>RDD_DS_TM_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1ac8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR */


/* >>>RDD_XGPON_REPORT_TABLE_ADDRESS_ARR */
uint32_t RDD_XGPON_REPORT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1ad0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_XGPON_REPORT_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_SCHEDULING_FLUSH_VECTOR_ADDRESS_ARR */
uint32_t RDD_DS_TM_SCHEDULING_FLUSH_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1ae0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_SCHEDULING_FLUSH_VECTOR_ADDRESS_ARR */


/* >>>RDD_GHOST_REPORTING_GLOBAL_CFG_ADDRESS_ARR */
uint32_t RDD_GHOST_REPORTING_GLOBAL_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1af4,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_GHOST_REPORTING_GLOBAL_CFG_ADDRESS_ARR */


/* >>>RDD_GENERAL_QUEUE_DYNAMIC_MNG_TABLE_ADDRESS_ARR */
uint32_t RDD_GENERAL_QUEUE_DYNAMIC_MNG_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1af8,
	0x3748,
	0x2608,
	0xef8,
	0xe08,
	0xa08,
};
/* <<<RDD_GENERAL_QUEUE_DYNAMIC_MNG_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1b00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR */


/* >>>RDD_BUDGET_ALLOCATION_TIMER_VALUE_ADDRESS_ARR */
uint32_t RDD_BUDGET_ALLOCATION_TIMER_VALUE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1b22,
	0x3374,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BUDGET_ALLOCATION_TIMER_VALUE_ADDRESS_ARR */


/* >>>RDD_DS_TM_BB_DESTINATION_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_BB_DESTINATION_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1b24,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_BB_DESTINATION_TABLE_ADDRESS_ARR */


/* >>>RDD_SCHEDULING_FLUSH_GLOBAL_CFG_ADDRESS_ARR */
uint32_t RDD_SCHEDULING_FLUSH_GLOBAL_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1b26,
	0x3574,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SCHEDULING_FLUSH_GLOBAL_CFG_ADDRESS_ARR */


/* >>>RDD_CORE_ID_TABLE_ADDRESS_ARR */
uint32_t RDD_CORE_ID_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1b27,
	0x37be,
	0x2bfd,
	0x2b65,
	0x2233,
	0xeff,
};
/* <<<RDD_CORE_ID_TABLE_ADDRESS_ARR */


/* >>>RDD_ACB_PORT_STATUS_TABLE_ADDRESS_ARR */
uint32_t RDD_ACB_PORT_STATUS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1b28,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_ACB_PORT_STATUS_TABLE_ADDRESS_ARR */


/* >>>RDD_QUEUE_TO_REPORT_BIT_VECTOR_ADDRESS_ARR */
uint32_t RDD_QUEUE_TO_REPORT_BIT_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1b30,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_QUEUE_TO_REPORT_BIT_VECTOR_ADDRESS_ARR */


/* >>>RDD_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1b40,
	0x3800,
	INVALID_TABLE_ADDRESS,
	0x2c40,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR */
uint32_t RDD_DS_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1b60,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR */


/* >>>RDD_TASK_IDX_ADDRESS_ARR */
uint32_t RDD_TASK_IDX_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1b74,
	0x33f4,
	0x2be4,
	0x261c,
	0x2234,
	0xfa4,
};
/* <<<RDD_TASK_IDX_ADDRESS_ARR */


/* >>>RDD_MIRRORING_SCRATCH_ADDRESS_ARR */
uint32_t RDD_MIRRORING_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1b78,
	0x3898,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_MIRRORING_SCRATCH_ADDRESS_ARR */


/* >>>RDD_DS_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR */
uint32_t RDD_DS_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1b80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR */


/* >>>RDD_TX_MIRRORING_CONFIGURATION_ADDRESS_ARR */
uint32_t RDD_TX_MIRRORING_CONFIGURATION_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1b94,
	0x37fc,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TX_MIRRORING_CONFIGURATION_ADDRESS_ARR */


/* >>>RDD_SRAM_DUMMY_STORE_ADDRESS_ARR */
uint32_t RDD_SRAM_DUMMY_STORE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1b96,
	0x37bf,
	0x2d62,
	0x2be4,
	0x22ee,
	0xf4d,
};
/* <<<RDD_SRAM_DUMMY_STORE_ADDRESS_ARR */


/* >>>RDD_RATE_LIMIT_OVERHEAD_ADDRESS_ARR */
uint32_t RDD_RATE_LIMIT_OVERHEAD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1b97,
	0x37fe,
	0x2d63,
	0x2be5,
	0x22ef,
	0xfbc,
};
/* <<<RDD_RATE_LIMIT_OVERHEAD_ADDRESS_ARR */


/* >>>RDD_REPORT_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR */
uint32_t RDD_REPORT_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1b98,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_REPORT_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR */


/* >>>RDD_GHOST_REPORTING_QUEUE_STATUS_BIT_VECTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_GHOST_REPORTING_QUEUE_STATUS_BIT_VECTOR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1ba0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_GHOST_REPORTING_QUEUE_STATUS_BIT_VECTOR_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_SCHEDULING_GLOBAL_FLUSH_CFG_ADDRESS_ARR */
uint32_t RDD_DS_TM_SCHEDULING_GLOBAL_FLUSH_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1bb4,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_SCHEDULING_GLOBAL_FLUSH_CFG_ADDRESS_ARR */


/* >>>RDD_DS_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR */
uint32_t RDD_DS_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1bb5,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR */


/* >>>RDD_DS_TM_FLUSH_AGGREGATION_TASK_DISABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_FLUSH_AGGREGATION_TASK_DISABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1bb6,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_FLUSH_AGGREGATION_TASK_DISABLE_ADDRESS_ARR */


/* >>>RDD_BBH_TX_INGRESS_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_BBH_TX_INGRESS_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1bb7,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BBH_TX_INGRESS_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_BBH_TX_EGRESS_REPORT_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_BBH_TX_EGRESS_REPORT_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1bb8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BBH_TX_EGRESS_REPORT_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_ACB_PACKET_SENT_PD_COPY_ADDRESS_ARR */
uint32_t RDD_ACB_PACKET_SENT_PD_COPY_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1bc0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_ACB_PACKET_SENT_PD_COPY_ADDRESS_ARR */


/* >>>RDD_DS_TM_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1bd0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_RATE_LIMITER_VALID_TABLE_DS_ADDRESS_ARR */
uint32_t RDD_RATE_LIMITER_VALID_TABLE_DS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1be0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_RATE_LIMITER_VALID_TABLE_DS_ADDRESS_ARR */


/* >>>RDD_TX_MIRRORING_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_TX_MIRRORING_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1bf0,
	0x38f0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TX_MIRRORING_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_BBH_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_BBH_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1c00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_BBH_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_FPM_GLOBAL_CFG_ADDRESS_ARR */
uint32_t RDD_FPM_GLOBAL_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1c20,
	0x3900,
	0x2fb0,
	0x2da0,
	0x31f0,
	0xfb0,
};
/* <<<RDD_FPM_GLOBAL_CFG_ADDRESS_ARR */


/* >>>RDD_XGPON_REPORT_ZERO_SENT_TABLE_ADDRESS_ARR */
uint32_t RDD_XGPON_REPORT_ZERO_SENT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1c30,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_XGPON_REPORT_ZERO_SENT_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1c40,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_EGRESS_PORT_RR_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_EGRESS_PORT_RR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1d00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_EGRESS_PORT_RR_TABLE_ADDRESS_ARR */


/* >>>RDD_REPORTING_QUEUE_DESCRIPTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_REPORTING_QUEUE_DESCRIPTOR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2000,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_REPORTING_QUEUE_DESCRIPTOR_TABLE_ADDRESS_ARR */


/* >>>RDD_DEBUG_TRACE_ADDRESS_ARR */
uint32_t RDD_DEBUG_TRACE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x3e00,
	0x3e00,
	0x3e00,
	0x3e00,
	0x3e00,
	0x3e00,
};
/* <<<RDD_DEBUG_TRACE_ADDRESS_ARR */


/* >>>RDD_DDR_PREFETCH_PINGPONG_BUFFER_ADDRESS_ARR */
uint32_t RDD_DDR_PREFETCH_PINGPONG_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DDR_PREFETCH_PINGPONG_BUFFER_ADDRESS_ARR */


/* >>>RDD_BASIC_RATE_LIMITER_TABLE_US_ADDRESS_ARR */
uint32_t RDD_BASIC_RATE_LIMITER_TABLE_US_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x1000,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BASIC_RATE_LIMITER_TABLE_US_ADDRESS_ARR */


/* >>>RDD_DDR_PREFETCH_PD_FIFO_ADDRESS_ARR */
uint32_t RDD_DDR_PREFETCH_PD_FIFO_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x1800,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DDR_PREFETCH_PD_FIFO_ADDRESS_ARR */


/* >>>RDD_US_TM_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2000,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_BASIC_SCHEDULER_TABLE_US_ADDRESS_ARR */
uint32_t RDD_BASIC_SCHEDULER_TABLE_US_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2a00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BASIC_SCHEDULER_TABLE_US_ADDRESS_ARR */


/* >>>RDD_US_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2c00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_RX_COMPLETE_FLOW_RING_BUFFER_ADDRESS_ARR */
uint32_t RDD_DHD_RX_COMPLETE_FLOW_RING_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2e80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_RX_COMPLETE_FLOW_RING_BUFFER_ADDRESS_ARR */


/* >>>RDD_US_TM_DSL_TM_FLOW_CNTR_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_DSL_TM_FLOW_CNTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2f00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_DSL_TM_FLOW_CNTR_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_COMPLETE_COMMON_RADIO_DATA_ADDRESS_ARR */
uint32_t RDD_DHD_COMPLETE_COMMON_RADIO_DATA_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3200,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_COMPLETE_COMMON_RADIO_DATA_ADDRESS_ARR */


/* >>>RDD_DHD_HW_CFG_ADDRESS_ARR */
uint32_t RDD_DHD_HW_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3350,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2210,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_HW_CFG_ADDRESS_ARR */


/* >>>RDD_US_TM_SCHEDULING_FLUSH_VECTOR_ADDRESS_ARR */
uint32_t RDD_US_TM_SCHEDULING_FLUSH_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3360,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_SCHEDULING_FLUSH_VECTOR_ADDRESS_ARR */


/* >>>RDD_US_TM_BB_DESTINATION_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_BB_DESTINATION_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3376,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_BB_DESTINATION_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_AE2P5_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_AE2P5_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3378,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_AE2P5_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_RX_POST_FLOW_RING_BUFFER_ADDRESS_ARR */
uint32_t RDD_DHD_RX_POST_FLOW_RING_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3380,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_RX_POST_FLOW_RING_BUFFER_ADDRESS_ARR */


/* >>>RDD_US_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR */
uint32_t RDD_US_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x33e0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR */


/* >>>RDD_US_TM_AE10_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_AE10_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x33f8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_AE10_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR */


/* >>>RDD_DDR_PREFETCH_SBPM_FIFO_ADDRESS_ARR */
uint32_t RDD_DDR_PREFETCH_SBPM_FIFO_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3400,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DDR_PREFETCH_SBPM_FIFO_ADDRESS_ARR */


/* >>>RDD_US_TM_DSL_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_DSL_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3548,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_DSL_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR */


/* >>>RDD_OVERALL_RATE_LIMITER_TABLE_ADDRESS_ARR */
uint32_t RDD_OVERALL_RATE_LIMITER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3550,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_OVERALL_RATE_LIMITER_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR */
uint32_t RDD_US_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3560,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR */


/* >>>RDD_US_TM_ETH_TM_FLOW_CNTR_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_ETH_TM_FLOW_CNTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3575,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_ETH_TM_FLOW_CNTR_TABLE_ADDRESS_ARR */


/* >>>RDD_TX_TASK_DDR_PREFETCH_FIFO_PTR_ADDRESS_ARR */
uint32_t RDD_TX_TASK_DDR_PREFETCH_FIFO_PTR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3576,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TX_TASK_DDR_PREFETCH_FIFO_PTR_ADDRESS_ARR */


/* >>>RDD_US_TM_PON_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_PON_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3578,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_PON_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_PON_TM_FLOW_CNTR_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_PON_TM_FLOW_CNTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3580,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_PON_TM_FLOW_CNTR_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_TX_COMPLETE_FLOW_RING_BUFFER_ADDRESS_ARR */
uint32_t RDD_DHD_TX_COMPLETE_FLOW_RING_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x35c0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_TX_COMPLETE_FLOW_RING_BUFFER_ADDRESS_ARR */


/* >>>RDD_US_TM_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x35f0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_DDR_READ_DDR_PREFETCH_FIFO_PTR_ADDRESS_ARR */
uint32_t RDD_DDR_READ_DDR_PREFETCH_FIFO_PTR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x35fc,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DDR_READ_DDR_PREFETCH_FIFO_PTR_ADDRESS_ARR */


/* >>>RDD_PSRAM_WRITE_DDR_PREFETCH_FIFO_PTR_ADDRESS_ARR */
uint32_t RDD_PSRAM_WRITE_DDR_PREFETCH_FIFO_PTR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x35fe,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PSRAM_WRITE_DDR_PREFETCH_FIFO_PTR_ADDRESS_ARR */


/* >>>RDD_US_TM_BBH_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_BBH_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3600,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_BBH_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3750,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_DDR_READ_DDR_PREFETCH_PINGPONG_BUFFER_PTR_ADDRESS_ARR */
uint32_t RDD_DDR_READ_DDR_PREFETCH_PINGPONG_BUFFER_PTR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x375c,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DDR_READ_DDR_PREFETCH_PINGPONG_BUFFER_PTR_ADDRESS_ARR */


/* >>>RDD_PSRAM_WRITE_DDR_PREFETCH_PINGPONG_BUFFER_PTR_ADDRESS_ARR */
uint32_t RDD_PSRAM_WRITE_DDR_PREFETCH_PINGPONG_BUFFER_PTR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x375e,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PSRAM_WRITE_DDR_PREFETCH_PINGPONG_BUFFER_PTR_ADDRESS_ARR */


/* >>>RDD_RATE_LIMITER_VALID_TABLE_US_ADDRESS_ARR */
uint32_t RDD_RATE_LIMITER_VALID_TABLE_US_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3760,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_RATE_LIMITER_VALID_TABLE_US_ADDRESS_ARR */


/* >>>RDD_WAN_TX_DDR_READ_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_WAN_TX_DDR_READ_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3770,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_WAN_TX_DDR_READ_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_WRITE_DDR_PREFETCH_SBPM_FIFO_PTR_ADDRESS_ARR */
uint32_t RDD_WRITE_DDR_PREFETCH_SBPM_FIFO_PTR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x377c,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_WRITE_DDR_PREFETCH_SBPM_FIFO_PTR_ADDRESS_ARR */


/* >>>RDD_READ_DDR_PREFETCH_SBPM_FIFO_PTR_ADDRESS_ARR */
uint32_t RDD_READ_DDR_PREFETCH_SBPM_FIFO_PTR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x377e,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_READ_DDR_PREFETCH_SBPM_FIFO_PTR_ADDRESS_ARR */


/* >>>RDD_DHD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3780,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3380,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */


/* >>>RDD_WAN_TX_PSRAM_WRITE_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_WAN_TX_PSRAM_WRITE_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x37b0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_WAN_TX_PSRAM_WRITE_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_TX_TASK_DDR_READ_DISP_BB_ID_ADDRESS_ARR */
uint32_t RDD_TX_TASK_DDR_READ_DISP_BB_ID_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x37bc,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TX_TASK_DDR_READ_DISP_BB_ID_ADDRESS_ARR */


/* >>>RDD_US_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x37c0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_RX_POST_RING_SIZE_ADDRESS_ARR */
uint32_t RDD_DHD_RX_POST_RING_SIZE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x37e2,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_RX_POST_RING_SIZE_ADDRESS_ARR */


/* >>>RDD_DHD_RX_COMPLETE_RING_SIZE_ADDRESS_ARR */
uint32_t RDD_DHD_RX_COMPLETE_RING_SIZE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x37e4,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_RX_COMPLETE_RING_SIZE_ADDRESS_ARR */


/* >>>RDD_DHD_TX_COMPLETE_RING_SIZE_ADDRESS_ARR */
uint32_t RDD_DHD_TX_COMPLETE_RING_SIZE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x37e6,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_TX_COMPLETE_RING_SIZE_ADDRESS_ARR */


/* >>>RDD_DHD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */
uint32_t RDD_DHD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x37e8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2fe8,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */


/* >>>RDD_DHD_RX_COMPLETE_0_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_RX_COMPLETE_0_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x37f0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_RX_COMPLETE_0_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_SCHEDULING_GLOBAL_FLUSH_CFG_ADDRESS_ARR */
uint32_t RDD_US_TM_SCHEDULING_GLOBAL_FLUSH_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x37ff,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_SCHEDULING_GLOBAL_FLUSH_CFG_ADDRESS_ARR */


/* >>>RDD_DHD_RX_COMPLETE_1_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_RX_COMPLETE_1_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3820,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_RX_COMPLETE_1_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_ETH_BBH_TX_FIFO_SIZE_ADDRESS_ARR */
uint32_t RDD_US_TM_ETH_BBH_TX_FIFO_SIZE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x382c,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_ETH_BBH_TX_FIFO_SIZE_ADDRESS_ARR */


/* >>>RDD_US_TM_DSL_BBH_TX_FIFO_SIZE_ADDRESS_ARR */
uint32_t RDD_US_TM_DSL_BBH_TX_FIFO_SIZE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x382d,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_DSL_BBH_TX_FIFO_SIZE_ADDRESS_ARR */


/* >>>RDD_US_TM_PON_BBH_TX_FIFO_SIZE_ADDRESS_ARR */
uint32_t RDD_US_TM_PON_BBH_TX_FIFO_SIZE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x382e,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_PON_BBH_TX_FIFO_SIZE_ADDRESS_ARR */


/* >>>RDD_US_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR */
uint32_t RDD_US_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x382f,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR */


/* >>>RDD_DHD_RX_COMPLETE_2_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_RX_COMPLETE_2_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3830,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_RX_COMPLETE_2_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_FLUSH_AGGREGATION_TASK_DISABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_FLUSH_AGGREGATION_TASK_DISABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x383c,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_FLUSH_AGGREGATION_TASK_DISABLE_ADDRESS_ARR */


/* >>>RDD_DDR_PREFETCH_PD_FIFO_CNTR_ADDRESS_ARR */
uint32_t RDD_DDR_PREFETCH_PD_FIFO_CNTR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x383d,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DDR_PREFETCH_PD_FIFO_CNTR_ADDRESS_ARR */


/* >>>RDD_DDR_PREFETCH_WAKEUP_FLAG_ADDRESS_ARR */
uint32_t RDD_DDR_PREFETCH_WAKEUP_FLAG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x383e,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DDR_PREFETCH_WAKEUP_FLAG_ADDRESS_ARR */


/* >>>RDD_US_TM_PON_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_PON_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3840,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_PON_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_TX_COMPLETE_0_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_TX_COMPLETE_0_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3860,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_TX_COMPLETE_0_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_TX_COMPLETE_1_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_TX_COMPLETE_1_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3870,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_TX_COMPLETE_1_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_FPM_REPLY_ADDRESS_ARR */
uint32_t RDD_DHD_FPM_REPLY_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3880,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_FPM_REPLY_ADDRESS_ARR */


/* >>>RDD_DHD_TX_COMPLETE_2_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_TX_COMPLETE_2_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x38a0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_TX_COMPLETE_2_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_DOORBELL_TX_COMPLETE_VALUE_ADDRESS_ARR */
uint32_t RDD_DHD_DOORBELL_TX_COMPLETE_VALUE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x38b0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_DOORBELL_TX_COMPLETE_VALUE_ADDRESS_ARR */


/* >>>RDD_US_TM_DSL_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_DSL_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x38c0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_DSL_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_DOORBELL_RX_COMPLETE_VALUE_ADDRESS_ARR */
uint32_t RDD_DHD_DOORBELL_RX_COMPLETE_VALUE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x38d0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_DOORBELL_RX_COMPLETE_VALUE_ADDRESS_ARR */


/* >>>RDD_DHD_DOORBELL_RX_POST_VALUE_ADDRESS_ARR */
uint32_t RDD_DHD_DOORBELL_RX_POST_VALUE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x38e0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_DOORBELL_RX_POST_VALUE_ADDRESS_ARR */


/* >>>RDD_US_TM_AE2P5_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_AE2P5_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3940,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_AE2P5_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_AE10_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_AE10_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3980,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_AE10_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_CPU_TX_SCRATCHPAD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_RX_FLOW_TABLE_ADDRESS_ARR */
uint32_t RDD_RX_FLOW_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x800,
	0x800,
	0x400,
	0x0,
};
/* <<<RDD_RX_FLOW_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_WAN_UDP_FILTER_CONTROL_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_WAN_UDP_FILTER_CONTROL_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xa94,
	0xa94,
	0x694,
	0x294,
};
/* <<<RDD_DS_WAN_UDP_FILTER_CONTROL_TABLE_ADDRESS_ARR */


/* >>>RDD_FPM_REPLY_ADDRESS_ARR */
uint32_t RDD_FPM_REPLY_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xa98,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_FPM_REPLY_ADDRESS_ARR */


/* >>>RDD_GLOBAL_DSCP_TO_PBITS_TABLE_ADDRESS_ARR */
uint32_t RDD_GLOBAL_DSCP_TO_PBITS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xac0,
	0xac0,
	0x6c0,
	0x2c0,
};
/* <<<RDD_GLOBAL_DSCP_TO_PBITS_TABLE_ADDRESS_ARR */


/* >>>RDD_DSCP_TO_PBITS_MAP_TABLE_ADDRESS_ARR */
uint32_t RDD_DSCP_TO_PBITS_MAP_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xb00,
	0x600,
	0x300,
	0x300,
};
/* <<<RDD_DSCP_TO_PBITS_MAP_TABLE_ADDRESS_ARR */


/* >>>RDD_TCAM_IC_CMD_TABLE_ADDRESS_ARR */
uint32_t RDD_TCAM_IC_CMD_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xc00,
	0xc00,
	0x800,
	0x400,
};
/* <<<RDD_TCAM_IC_CMD_TABLE_ADDRESS_ARR */


/* >>>RDD_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR */
uint32_t RDD_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xe40,
	0xbc0,
	0xbc0,
	0x640,
};
/* <<<RDD_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xe80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR */


/* >>>RDD_PON_TX_FLOW_TABLE_ADDRESS_ARR */
uint32_t RDD_PON_TX_FLOW_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xec0,
	0xe40,
	0xe40,
	0x680,
};
/* <<<RDD_PON_TX_FLOW_TABLE_ADDRESS_ARR */


/* >>>RDD_DSL_TX_FLOW_TABLE_ADDRESS_ARR */
uint32_t RDD_DSL_TX_FLOW_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xf00,
	0x700,
	0x700,
	0x700,
};
/* <<<RDD_DSL_TX_FLOW_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_PACKET_BUFFER_ADDRESS_ARR */
uint32_t RDD_DS_PACKET_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x1000,
	0x1000,
	0x1000,
	0x1000,
};
/* <<<RDD_DS_PACKET_BUFFER_ADDRESS_ARR */


/* >>>RDD_TC_TO_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_TC_TO_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2000,
	0x2000,
	0xc00,
	0x800,
};
/* <<<RDD_TC_TO_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_IPTV_CONFIGURATION_TABLE_ADDRESS_ARR */
uint32_t RDD_IPTV_CONFIGURATION_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2208,
	0xa98,
	0x698,
	0x298,
};
/* <<<RDD_IPTV_CONFIGURATION_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_WAN_UDP_FILTER_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_WAN_UDP_FILTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2210,
	0xb90,
	0xf90,
	0xa10,
};
/* <<<RDD_DS_WAN_UDP_FILTER_TABLE_ADDRESS_ARR */


/* >>>RDD_VPORT_TO_DSCP_TO_PBITS_TABLE_ADDRESS_ARR */
uint32_t RDD_VPORT_TO_DSCP_TO_PBITS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2220,
	0xaa0,
	0xe20,
	0xa20,
};
/* <<<RDD_VPORT_TO_DSCP_TO_PBITS_TABLE_ADDRESS_ARR */


/* >>>RDD_VPORT_TX_FLOW_TABLE_ADDRESS_ARR */
uint32_t RDD_VPORT_TX_FLOW_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2240,
	0x2240,
	0xfc0,
	0x6c0,
};
/* <<<RDD_VPORT_TX_FLOW_TABLE_ADDRESS_ARR */


/* >>>RDD_PBIT_TO_GEM_TABLE_ADDRESS_ARR */
uint32_t RDD_PBIT_TO_GEM_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2280,
	0x22c0,
	0x2240,
	0xa40,
};
/* <<<RDD_PBIT_TO_GEM_TABLE_ADDRESS_ARR */


/* >>>RDD_DUAL_STACK_LITE_TABLE_ADDRESS_ARR */
uint32_t RDD_DUAL_STACK_LITE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x22c0,
	0x2380,
	0x2380,
	0xa80,
};
/* <<<RDD_DUAL_STACK_LITE_TABLE_ADDRESS_ARR */


/* >>>RDD_QM_QUEUE_TO_TX_FLOW_TABLE_PTR_TABLE_ADDRESS_ARR */
uint32_t RDD_QM_QUEUE_TO_TX_FLOW_TABLE_PTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2300,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_QM_QUEUE_TO_TX_FLOW_TABLE_PTR_TABLE_ADDRESS_ARR */


/* >>>RDD_PBIT_TO_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_PBIT_TO_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2400,
	0x2400,
	0x2000,
	0xc00,
};
/* <<<RDD_PBIT_TO_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2610,
	0xff0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR */


/* >>>RDD_VPORT_TO_LOOKUP_PORT_MAPPING_TABLE_ADDRESS_ARR */
uint32_t RDD_VPORT_TO_LOOKUP_PORT_MAPPING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2620,
	0xba0,
	0xee0,
	0xea0,
};
/* <<<RDD_VPORT_TO_LOOKUP_PORT_MAPPING_TABLE_ADDRESS_ARR */


/* >>>RDD_GPE_COMMAND_PRIMITIVE_TABLE_ADDRESS_ARR */
uint32_t RDD_GPE_COMMAND_PRIMITIVE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2640,
	0x23c0,
	0x23c0,
	0xac0,
};
/* <<<RDD_GPE_COMMAND_PRIMITIVE_TABLE_ADDRESS_ARR */


/* >>>RDD_INGRESS_FILTER_PROFILE_TABLE_ADDRESS_ARR */
uint32_t RDD_INGRESS_FILTER_PROFILE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2700,
	0xf00,
	0x2300,
	0xb00,
};
/* <<<RDD_INGRESS_FILTER_PROFILE_TABLE_ADDRESS_ARR */


/* >>>RDD_TCAM_IC_CFG_TABLE_ADDRESS_ARR */
uint32_t RDD_TCAM_IC_CFG_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2780,
	0x2780,
	0x3140,
	0xe20,
};
/* <<<RDD_TCAM_IC_CFG_TABLE_ADDRESS_ARR */


/* >>>RDD_LAYER2_GRE_TUNNEL_TABLE_ADDRESS_ARR */
uint32_t RDD_LAYER2_GRE_TUNNEL_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2a00,
	0x200,
	0x2a00,
	0x2200,
};
/* <<<RDD_LAYER2_GRE_TUNNEL_TABLE_ADDRESS_ARR */


/* >>>RDD_LOOPBACK_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_LOOPBACK_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b80,
	0x2b00,
	0x2fc0,
	0xec0,
};
/* <<<RDD_LOOPBACK_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_PROCESSING_QUEUE_DYNAMIC_MNG_TABLE_ADDRESS_ARR */
uint32_t RDD_PROCESSING_QUEUE_DYNAMIC_MNG_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2ba8,
	0x2208,
	0x2208,
	0xe08,
};
/* <<<RDD_PROCESSING_QUEUE_DYNAMIC_MNG_TABLE_ADDRESS_ARR */


/* >>>RDD_INGRESS_FILTER_L2_REASON_TABLE_ADDRESS_ARR */
uint32_t RDD_INGRESS_FILTER_L2_REASON_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2bb0,
	0x2350,
	0x22d0,
	0xe10,
};
/* <<<RDD_INGRESS_FILTER_L2_REASON_TABLE_ADDRESS_ARR */


/* >>>RDD_QUEUE_THRESHOLD_VECTOR_ADDRESS_ARR */
uint32_t RDD_QUEUE_THRESHOLD_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2bc0,
	0x2b40,
	0x3340,
	0xf80,
};
/* <<<RDD_QUEUE_THRESHOLD_VECTOR_ADDRESS_ARR */


/* >>>RDD_RX_FLOW_CONTEXT_DDR_ADDR_ADDRESS_ARR */
uint32_t RDD_RX_FLOW_CONTEXT_DDR_ADDR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2be8,
	0x2348,
	0x2238,
	0xee8,
};
/* <<<RDD_RX_FLOW_CONTEXT_DDR_ADDR_ADDRESS_ARR */


/* >>>RDD_CPU_TX_EGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_EGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2bf0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_EGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_FORCE_DSCP_ADDRESS_ARR */
uint32_t RDD_FORCE_DSCP_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2bfc,
	0x2b64,
	0x2232,
	0xefe,
};
/* <<<RDD_FORCE_DSCP_ADDRESS_ARR */


/* >>>RDD_RX_MIRRORING_CONFIGURATION_ADDRESS_ARR */
uint32_t RDD_RX_MIRRORING_CONFIGURATION_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2bfe,
	0x2be2,
	0x22ec,
	0xf4e,
};
/* <<<RDD_RX_MIRRORING_CONFIGURATION_ADDRESS_ARR */


/* >>>RDD_VPORT_CFG_TABLE_ADDRESS_ARR */
uint32_t RDD_VPORT_CFG_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2c00,
	0x0,
	0x3000,
	0x2400,
};
/* <<<RDD_VPORT_CFG_TABLE_ADDRESS_ARR */


/* >>>RDD_FLOW_BASED_ACTION_PTR_TABLE_ADDRESS_ARR */
uint32_t RDD_FLOW_BASED_ACTION_PTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2d40,
	0x2bc0,
	0x33c0,
	0xfc0,
};
/* <<<RDD_FLOW_BASED_ACTION_PTR_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_RECYCLE_RING_ID_ADDRESS_ARR */
uint32_t RDD_CPU_TX_RECYCLE_RING_ID_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2d64,
	0x2be7,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_RECYCLE_RING_ID_ADDRESS_ARR */


/* >>>RDD_CPU_REDIRECT_MODE_ADDRESS_ARR */
uint32_t RDD_CPU_REDIRECT_MODE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2d65,
	0x2bed,
	0x31ee,
	0xfbd,
};
/* <<<RDD_CPU_REDIRECT_MODE_ADDRESS_ARR */


/* >>>RDD_IPTV_CLASSIFICATION_CFG_TABLE_ADDRESS_ARR */
uint32_t RDD_IPTV_CLASSIFICATION_CFG_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2d66,
	0x2bee,
	0x31ef,
	0xfbe,
};
/* <<<RDD_IPTV_CLASSIFICATION_CFG_TABLE_ADDRESS_ARR */


/* >>>RDD_INGRESS_FILTER_1588_CFG_ADDRESS_ARR */
uint32_t RDD_INGRESS_FILTER_1588_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2d67,
	0x2bef,
	0x31fc,
	0xfbf,
};
/* <<<RDD_INGRESS_FILTER_1588_CFG_ADDRESS_ARR */


/* >>>RDD_NULL_BUFFER_ADDRESS_ARR */
uint32_t RDD_NULL_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2d68,
	0x2608,
	0x22c8,
	0xef0,
};
/* <<<RDD_NULL_BUFFER_ADDRESS_ARR */


/* >>>RDD_CPU_TX_INGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_INGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2d70,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_INGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_RX_MIRRORING_DIRECT_ENABLE_ADDRESS_ARR */
uint32_t RDD_RX_MIRRORING_DIRECT_ENABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2d7c,
	0x2c22,
	0x31fd,
	0xfe2,
};
/* <<<RDD_RX_MIRRORING_DIRECT_ENABLE_ADDRESS_ARR */


/* >>>RDD_VLAN_ACTION_GPE_HANDLER_PTR_TABLE_ADDRESS_ARR */
uint32_t RDD_VLAN_ACTION_GPE_HANDLER_PTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2d80,
	0x2c00,
	0x34c0,
	0x2380,
};
/* <<<RDD_VLAN_ACTION_GPE_HANDLER_PTR_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2da8,
	0x2b28,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2db0,
	0x2b30,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_EGRESS_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_EGRESS_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2dc0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_EGRESS_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_TCAM_IC_HANDLER_TABLE_ADDRESS_ARR */
uint32_t RDD_TCAM_IC_HANDLER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2de0,
	0x2620,
	0xfa0,
	0xf60,
};
/* <<<RDD_TCAM_IC_HANDLER_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_SRAM_PD_FIFO_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_SRAM_PD_FIFO_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2e00,
	0x2a00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_SRAM_PD_FIFO_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_RING_INDEX_DDR_ADDR_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_RING_INDEX_DDR_ADDR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2f48,
	0x2b68,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_RING_INDEX_DDR_ADDR_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */
uint32_t RDD_CPU_RX_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2f58,
	0x2b78,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */


/* >>>RDD_BROADCOM_SWITCH_PORT_TO_RX_FLOW_MAPPING_TABLE_ADDRESS_ARR */
uint32_t RDD_BROADCOM_SWITCH_PORT_TO_RX_FLOW_MAPPING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2f60,
	0x2c60,
	0x2220,
	0x23c0,
};
/* <<<RDD_BROADCOM_SWITCH_PORT_TO_RX_FLOW_MAPPING_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_FPM_THRESHOLDS_ADDRESS_ARR */
uint32_t RDD_DHD_FPM_THRESHOLDS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2f78,
	0x2ba8,
	0x31e8,
	0xef8,
};
/* <<<RDD_DHD_FPM_THRESHOLDS_ADDRESS_ARR */


/* >>>RDD_CPU_TX_INGRESS_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_INGRESS_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2f80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_INGRESS_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_FEED_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_FEED_RING_DESCRIPTOR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2fa0,
	0x2bf0,
	0x22f0,
	0xf50,
};
/* <<<RDD_CPU_FEED_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_EGRESS_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_EGRESS_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2fc0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_EGRESS_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_SYSTEM_CONFIGURATION_ADDRESS_ARR */
uint32_t RDD_SYSTEM_CONFIGURATION_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2fe0,
	0x2be8,
	0x3338,
	0xf48,
};
/* <<<RDD_SYSTEM_CONFIGURATION_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2fe8,
	0x2c38,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_TUNNELS_PARSING_CFG_ADDRESS_ARR */
uint32_t RDD_TUNNELS_PARSING_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2ff0,
	0x2db0,
	0x3368,
	0xfa8,
};
/* <<<RDD_TUNNELS_PARSING_CFG_ADDRESS_ARR */


/* >>>RDD_IPTV_CFG_TABLE_ADDRESS_ARR */
uint32_t RDD_IPTV_CFG_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2ff8,
	0x2db8,
	0x3370,
	0xfe8,
};
/* <<<RDD_IPTV_CFG_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_INGRESS_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_INGRESS_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3000,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_INGRESS_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_IPTV_DDR_CTX_TABLE_ADDRESS_ADDRESS_ARR */
uint32_t RDD_IPTV_DDR_CTX_TABLE_ADDRESS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3020,
	0x2de8,
	0x3378,
	0xff0,
};
/* <<<RDD_IPTV_DDR_CTX_TABLE_ADDRESS_ADDRESS_ARR */


/* >>>RDD_NAT_CACHE_CFG_ADDRESS_ARR */
uint32_t RDD_NAT_CACHE_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3028,
	0x2df0,
	0x33b0,
	0xff8,
};
/* <<<RDD_NAT_CACHE_CFG_ADDRESS_ARR */


/* >>>RDD_POST_LOOKUP_CFG_ADDRESS_ARR */
uint32_t RDD_POST_LOOKUP_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3030,
	0x2df8,
	0x33b8,
	0x23a8,
};
/* <<<RDD_POST_LOOKUP_CFG_ADDRESS_ARR */


/* >>>RDD_NAT_CACHE_KEY0_MASK_ADDRESS_ARR */
uint32_t RDD_NAT_CACHE_KEY0_MASK_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3038,
	0x2e08,
	0x33e8,
	0x23b0,
};
/* <<<RDD_NAT_CACHE_KEY0_MASK_ADDRESS_ARR */


/* >>>RDD_NATC_L2_VLAN_KEY_MASK_ADDRESS_ARR */
uint32_t RDD_NATC_L2_VLAN_KEY_MASK_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3040,
	0x2e18,
	0x33f0,
	0x23b8,
};
/* <<<RDD_NATC_L2_VLAN_KEY_MASK_ADDRESS_ARR */


/* >>>RDD_INGRESS_FILTER_CFG_ADDRESS_ARR */
uint32_t RDD_INGRESS_FILTER_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3048,
	0x2e20,
	0x33f8,
	0x23d8,
};
/* <<<RDD_INGRESS_FILTER_CFG_ADDRESS_ARR */


/* >>>RDD_NATC_L2_TOS_MASK_ADDRESS_ARR */
uint32_t RDD_NATC_L2_TOS_MASK_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3050,
	0x2e28,
	0x34e8,
	0x23e0,
};
/* <<<RDD_NATC_L2_TOS_MASK_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_INTERRUPT_SCRATCH_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_INTERRUPT_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3080,
	0x2e00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_INTERRUPT_SCRATCH_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_SHADOW_RD_IDX_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_SHADOW_RD_IDX_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3100,
	0x2e80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_SHADOW_RD_IDX_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_SHADOW_WR_IDX_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_SHADOW_WR_IDX_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3180,
	0x2f00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_SHADOW_WR_IDX_ADDRESS_ARR */


/* >>>RDD_FC_FLOW_IP_ADDRESSES_TABLE_ADDRESS_ARR */
uint32_t RDD_FC_FLOW_IP_ADDRESSES_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3d00,
	0x3d00,
	0x3d00,
	0x3d00,
};
/* <<<RDD_FC_FLOW_IP_ADDRESSES_TABLE_ADDRESS_ARR */


/* >>>RDD_DIRECT_PROCESSING_PD_TABLE_ADDRESS_ARR */
uint32_t RDD_DIRECT_PROCESSING_PD_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x140,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DIRECT_PROCESSING_PD_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_CPU_RX_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_CPU_RX_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x180,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_CPU_RX_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_US_CPU_RX_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_US_CPU_RX_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x380,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_CPU_RX_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_CPU_RX_SCRATCHPAD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x400,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_CPU_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xb00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_REASON_AND_VPORT_TO_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_REASON_AND_VPORT_TO_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xe80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_REASON_AND_VPORT_TO_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_CSO_CONTEXT_TABLE_ADDRESS_ARR */
uint32_t RDD_CSO_CONTEXT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xf80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CSO_CONTEXT_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_INTERRUPT_SCRATCH_ADDRESS_ARR */
uint32_t RDD_CPU_RX_INTERRUPT_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xfec,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_INTERRUPT_SCRATCH_ADDRESS_ARR */


/* >>>RDD_CPU_RX_PSRAM_GET_NEXT_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_CPU_RX_PSRAM_GET_NEXT_SCRATCHPAD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2210,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_PSRAM_GET_NEXT_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_CPU_FEED_RING_RSV_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_FEED_RING_RSV_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2220,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_FEED_RING_RSV_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_COPY_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RX_COPY_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2280,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_COPY_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_IPV4_HOST_ADDRESS_TABLE_ADDRESS_ARR */
uint32_t RDD_IPV4_HOST_ADDRESS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2360,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_IPV4_HOST_ADDRESS_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_COPY_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RX_COPY_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2610,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_COPY_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2640,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_US_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_US_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2680,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_IPV6_HOST_ADDRESS_CRC_TABLE_ADDRESS_ARR */
uint32_t RDD_IPV6_HOST_ADDRESS_CRC_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x26c0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_IPV6_HOST_ADDRESS_CRC_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_FEED_RING_INTERRUPT_THRESHOLD_ADDRESS_ARR */
uint32_t RDD_CPU_FEED_RING_INTERRUPT_THRESHOLD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b66,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_FEED_RING_INTERRUPT_THRESHOLD_ADDRESS_ARR */


/* >>>RDD_CPU_VPORT_TO_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_VPORT_TO_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_VPORT_TO_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_FEED_RING_INTERRUPT_COUNTER_ADDRESS_ARR */
uint32_t RDD_CPU_FEED_RING_INTERRUPT_COUNTER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2bae,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_FEED_RING_INTERRUPT_COUNTER_ADDRESS_ARR */


/* >>>RDD_CPU_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2bb0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR */


/* >>>RDD_MAC_TYPE_ADDRESS_ARR */
uint32_t RDD_MAC_TYPE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2be6,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_MAC_TYPE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_LOCAL_SCRATCH_ADDRESS_ARR */
uint32_t RDD_CPU_RX_LOCAL_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2c28,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_LOCAL_SCRATCH_ADDRESS_ARR */


/* >>>RDD_CPU_RX_COPY_LOCAL_SCRATCH_ADDRESS_ARR */
uint32_t RDD_CPU_RX_COPY_LOCAL_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2c78,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_COPY_LOCAL_SCRATCH_ADDRESS_ARR */


/* >>>RDD_CPU_RX_COPY_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RX_COPY_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2c80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_COPY_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_SCRATCH_ADDRESS_ARR */
uint32_t RDD_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2ca0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SCRATCH_ADDRESS_ARR */


/* >>>RDD_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2cc0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_REASON_TO_TC_ADDRESS_ARR */
uint32_t RDD_CPU_REASON_TO_TC_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2ce0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_REASON_TO_TC_ADDRESS_ARR */


/* >>>RDD_TC_TO_CPU_RXQ_ADDRESS_ARR */
uint32_t RDD_TC_TO_CPU_RXQ_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2d20,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TC_TO_CPU_RXQ_ADDRESS_ARR */


/* >>>RDD_EXC_TC_TO_CPU_RXQ_ADDRESS_ARR */
uint32_t RDD_EXC_TC_TO_CPU_RXQ_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2d60,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_EXC_TC_TO_CPU_RXQ_ADDRESS_ARR */


/* >>>RDD_VPORT_TO_CPU_OBJ_ADDRESS_ARR */
uint32_t RDD_VPORT_TO_CPU_OBJ_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2dc0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_VPORT_TO_CPU_OBJ_ADDRESS_ARR */


/* >>>RDD_DIRECT_PROCESSING_EPON_CONTROL_SCRATCH_ADDRESS_ARR */
uint32_t RDD_DIRECT_PROCESSING_EPON_CONTROL_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2e10,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DIRECT_PROCESSING_EPON_CONTROL_SCRATCH_ADDRESS_ARR */


/* >>>RDD_CPU_RING_DESCRIPTORS_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RING_DESCRIPTORS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3000,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RING_DESCRIPTORS_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_FLOW_RING_CACHE_CTX_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_FLOW_RING_CACHE_CTX_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_FLOW_RING_CACHE_CTX_TABLE_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_SSID_STATS_TABLE_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_SSID_STATS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xa40,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_WLAN_MCAST_SSID_STATS_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xe10,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_BACKUP_INDEX_CACHE_ADDRESS_ARR */
uint32_t RDD_DHD_BACKUP_INDEX_CACHE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xe80,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_BACKUP_INDEX_CACHE_ADDRESS_ARR */


/* >>>RDD_DHD_TX_POST_FLOW_RING_BUFFER_ADDRESS_ARR */
uint32_t RDD_DHD_TX_POST_FLOW_RING_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xf00,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_TX_POST_FLOW_RING_BUFFER_ADDRESS_ARR */


/* >>>RDD_DHD_L2_HEADER_ADDRESS_ARR */
uint32_t RDD_DHD_L2_HEADER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2280,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_L2_HEADER_ADDRESS_ARR */


/* >>>RDD_DHD_MCAST_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_MCAST_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x22e0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_MCAST_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_COPY_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_COPY_SCRATCHPAD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2600,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_WLAN_MCAST_COPY_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_DHD_STATION_TABLE_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_DHD_STATION_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2800,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_WLAN_MCAST_DHD_STATION_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_BACKUP_INFO_CACHE_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_BACKUP_INFO_CACHE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2c00,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_BACKUP_INFO_CACHE_TABLE_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_DHD_STATION_CTX_TABLE_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_DHD_STATION_CTX_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2d80,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_WLAN_MCAST_DHD_STATION_CTX_TABLE_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_DFT_LIST_ENTRY_SCRATCH_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_DFT_LIST_ENTRY_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2dc0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_WLAN_MCAST_DFT_LIST_ENTRY_SCRATCH_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_SSID_MAC_ADDRESS_TABLE_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_SSID_MAC_ADDRESS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2e00,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_WLAN_MCAST_SSID_MAC_ADDRESS_TABLE_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_DFT_LIST_SIZE_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_DFT_LIST_SIZE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2f80,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_WLAN_MCAST_DFT_LIST_SIZE_ADDRESS_ARR */


/* >>>RDD_DHD_BACKUP_BASE_ADDR_ADDRESS_ARR */
uint32_t RDD_DHD_BACKUP_BASE_ADDR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2ff0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_BACKUP_BASE_ADDR_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_DFT_ADDR_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_DFT_ADDR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2ff8,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_WLAN_MCAST_DFT_ADDR_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_SCRATCHPAD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x31c0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_WLAN_MCAST_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_DHD_POST_COMMON_RADIO_DATA_ADDRESS_ARR */
uint32_t RDD_DHD_POST_COMMON_RADIO_DATA_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3200,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_POST_COMMON_RADIO_DATA_ADDRESS_ARR */


/* >>>RDD_DHD_TX_POST_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_TX_POST_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3400,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_TX_POST_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_FLOW_RING_CACHE_LKP_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_FLOW_RING_CACHE_LKP_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3500,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_FLOW_RING_CACHE_LKP_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_TX_POST_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_TX_POST_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3580,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_TX_POST_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_MCAST_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_MCAST_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x35c0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_MCAST_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_MCAST_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_MCAST_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3680,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_MCAST_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_DOORBELL_TX_POST_VALUE_ADDRESS_ARR */
uint32_t RDD_DHD_DOORBELL_TX_POST_VALUE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x36a0,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_DOORBELL_TX_POST_VALUE_ADDRESS_ARR */

