#ifndef IMAGE_0_CODE_ADDRESSES
#define IMAGE_0_CODE_ADDRESSES

#define image_0_start_task_initialization_task		(0x58)
#define image_0_initialization_task		(0x58)
#define image_0_start_task_update_fifo_us_read_1st_wakeup_request		(0x67C)
#define image_0_update_fifo_us_read_1st_wakeup_request		(0x67C)
#define image_0_start_task_ghost_reporting_1st_wakeup_request		(0x19FC)
#define image_0_ghost_reporting_1st_wakeup_request		(0x19FC)
#define image_0_start_task_tx_task_1st_wakeup_request		(0x17C)
#define image_0_tx_task_1st_wakeup_request		(0x17C)
#define image_0_start_task_epon_update_fifo_read_1st_wakeup_request		(0x914)
#define image_0_epon_update_fifo_read_1st_wakeup_request		(0x914)
#define image_0_start_task_epon_tx_task_wakeup_request		(0x1D54)
#define image_0_epon_tx_task_wakeup_request		(0x1D54)
#define image_0_start_task_budget_allocator_us_1st_wakeup_request		(0x1168)
#define image_0_budget_allocator_us_1st_wakeup_request		(0x1168)
#define image_0_start_task_debug_routine		(0x90)
#define image_0_debug_routine		(0x90)
#define image_0_start_task_ds_tx_task_wakeup_request		(0xCDC)
#define image_0_ds_tx_task_wakeup_request		(0xCDC)
#define image_0_start_task_ovl_budget_allocator_1st_wakeup_request		(0x14D0)
#define image_0_ovl_budget_allocator_1st_wakeup_request		(0x14D0)
#define image_0_start_task_flush_task_1st_wakeup_request		(0x1858)
#define image_0_flush_task_1st_wakeup_request		(0x1858)
#define image_0_start_task_update_fifo_ds_read_1st_wakeup_request		(0xA44)
#define image_0_update_fifo_ds_read_1st_wakeup_request		(0xA44)
#define image_0_start_task_budget_allocator_ds_1st_wakeup_request		(0x119C)
#define image_0_budget_allocator_ds_1st_wakeup_request		(0x119C)
#define image_0_start_task_flow_ctrl_task_wakeup_request		(0x1E40)
#define image_0_flow_ctrl_task_wakeup_request		(0x1E40)
#define image_0_start_task_service_queues_update_fifo_read_1st_wakeup_request		(0x1EC4)
#define image_0_service_queues_update_fifo_read_1st_wakeup_request		(0x1EC4)
#define image_0_start_task_service_queues_tx_task_wakeup_request		(0x1F54)
#define image_0_service_queues_tx_task_wakeup_request		(0x1F54)
#define image_0_start_task_budget_allocator_1st_wakeup_request		(0x2180)
#define image_0_budget_allocator_1st_wakeup_request		(0x2180)
#define image_0_debug_routine_handler		(0xC)
#define image_0_scheduling_update_status		(0x538)
#define image_0_scheduling_action_not_valid		(0x61C)
#define image_0_basic_scheduler_update_dwrr		(0xA20)
#define image_0_ds_tx_scheduling_update_status		(0xF70)
#define image_0_ds_tx_scheduling_action_not_valid		(0xFFC)
#define image_0_complex_scheduler_update_dwrr_basic_schedulers		(0x1134)
#define image_0_complex_scheduler_update_dwrr_queues		(0x1144)
#define image_0_basic_rate_limiter_complex_scheduler		(0x15A4)
#define image_0_basic_rate_limiter_basic_scheduler_no_cs		(0x15DC)
#define image_0_basic_rate_limiter_queue_with_cs_bs		(0x1610)
#define image_0_basic_rate_limiter_queue_with_bs		(0x1664)
#define image_0_ovl_rate_limiter		(0x16A0)
#define image_0_complex_rate_limiter_queue_sir		(0x16B4)
#define image_0_complex_rate_limiter_queue_pir		(0x16F0)
#define image_0_complex_rate_limiter_basic_scheduler_sir		(0x172C)
#define image_0_complex_rate_limiter_basic_scheduler_pir		(0x1768)
#define image_0_scheduling_service_queues_update_status		(0x2064)
#define image_0_scheduling_service_queues_action_not_valid		(0x2148)

#endif
