cmd_scripts/mod/empty.o := /opt/toolchains//crosstools-aarch64-gcc-5.5-linux-4.1-glibc-2.26-binutils-2.28.1/usr/bin/aarch64-buildroot-linux-gnu-gcc -Wp,-MD,scripts/mod/.empty.o.d  -nostdinc -isystem /opt/toolchains/crosstools-aarch64-gcc-5.5-linux-4.1-glibc-2.26-binutils-2.28.1/lib/gcc/aarch64-buildroot-linux-gnu/5.5.0/include -I./arch/arm64/include -Iarch/arm64/include/generated/uapi -Iarch/arm64/include/generated  -Iinclude -I./arch/arm64/include/uapi -Iarch/arm64/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -DMULTIPLE_SSID -DSAMBA_ENABLE -DX_ST_ML -DU12H315 -DR8000 -DR7800 -DU12H334 -DAX11000 -DBCM53125 -DINCLUDE_USB_LED -DWIFI_LED_BLINKING -DIGMP_PROXY -D__CONFIG_IGMP_SNOOPING__ -DINCLUDE_L2TP -DAP_MODE -DINCLUDE_DUAL_BAND -DCONFIG_RUSSIA_IPTV -DCONFIG_KERNEL_2_6_36 -DINCLUDE_ACCESSCONTROL -DINCLUDE_DETECT_AP_MODE -DARP_PROTECTION -DVLAN_SUPPORT -DINCLULDE_2ND_5G_RADIO -DDUAL_TRI_BAND_HW_SUPPORT -DCONFIG_2ND_SWITCH -DSUPPORT_2DOT5G_WAN -DU12H335T21 -D__FOXCONN_KERNEL_PORTING__ -DCONFIG_NAT_65536_SESSION -DWW_VERSION -DBCMVISTAROUTER -DINCLUDE_QOS -DRESTART_ALL_PROCESSES -DNETGEAR_PATCH -DETEROBO -mgeneral-regs-only -fno-delete-null-pointer-checks -fno-PIE -O2 --param=allow-store-data-races=0 -DCC_HAVE_ASM_GOTO -Wframe-larger-than=2048 -fno-stack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -DBCA_HNDROUTER    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(empty)"  -D"KBUILD_MODNAME=KBUILD_STR(empty)" -c -o scripts/mod/empty.o scripts/mod/empty.c

source_scripts/mod/empty.o := scripts/mod/empty.c

deps_scripts/mod/empty.o := \

scripts/mod/empty.o: $(deps_scripts/mod/empty.o)

$(deps_scripts/mod/empty.o):
