#ifndef RUNNER_C_CODE_ADDRESSES
#define RUNNER_C_CODE_ADDRESSES

#define runner_c_start_task_initialization_task		(0x14)
#define runner_c_initialization_task		(0x14)
#define runner_c_start_task_timer_scheduler_set		(0x7EC)
#define runner_c_timer_scheduler_set		(0x7EC)
#define runner_c_start_task_lan_tx_wakeup_request		(0x430)
#define runner_c_lan_tx_wakeup_request		(0x430)
#define runner_c_start_task_cpu_tx_wakeup_request		(0xA78)
#define runner_c_cpu_tx_wakeup_request		(0xA78)
#define runner_c_start_task_lan_enqueue_ih_wakeup_request		(0x1C4)
#define runner_c_lan_enqueue_ih_wakeup_request		(0x1C4)
#define runner_c_start_task_lan_enqueue_pd_wakeup_request		(0x208)
#define runner_c_lan_enqueue_pd_wakeup_request		(0x208)
#define runner_c_start_task_multicast_lan_enqueue_wakeup_request		(0x258)
#define runner_c_multicast_lan_enqueue_wakeup_request		(0x258)
#define runner_c_start_task_wlan_mcast_wakeup_request		(0x2E68)
#define runner_c_wlan_mcast_wakeup_request		(0x2E68)
#define runner_c_start_task_cpu_rx_int_coalesce_timer_1st_wakeup_request		(0x9C0)
#define runner_c_cpu_rx_int_coalesce_timer_1st_wakeup_request		(0x9C0)
#define runner_c_start_task_debug_routine		(0xDC)
#define runner_c_debug_routine		(0xDC)
#define runner_c_start_task_gso_wakeup_request		(0x1D58)
#define runner_c_gso_wakeup_request		(0x1D58)
#define runner_c_start_task_spdsvc_timer_1st_wakeup_request		(0xF58)
#define runner_c_spdsvc_timer_1st_wakeup_request		(0xF58)
#define runner_c_start_task_free_skb_index_wakeup_request		(0x95C)
#define runner_c_free_skb_index_wakeup_request		(0x95C)
#define runner_c_start_task_service_queue_dequeue_wakeup_request		(0x37A0)
#define runner_c_service_queue_dequeue_wakeup_request		(0x37A0)
#define runner_c_start_task_service_queue_enqueue_wakeup_request		(0x3870)
#define runner_c_service_queue_enqueue_wakeup_request		(0x3870)
#define runner_c_ds_rate_limiter_budget_allocate		(0x86C)
#define runner_c_ds_service_queue_rate_limiter_budget_allocate		(0x928)
#define runner_c_schedule_free_skb_index		(0x940)

#endif
