/*
   Copyright (c) 2015 Broadcom
   All Rights Reserved

    <:label-BRCM:2015:DUAL/GPL:standard
    
    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License, version 2, as published by
    the Free Software Foundation (the "GPL").
    
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
    
    
    A copy of the GPL is available at http://www.broadcom.com/licenses/GPLv2.php, or by
    writing to the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
    Boston, MA 02111-1307, USA.
    
:>
*/



/* This is an automated file. Do not edit its contents. */


#include "rdd.h"
#include "ru_types.h"

#include "rdd_data_structures_auto.h"

/* >>>RDD_DS_TM_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_COMPLEX_SCHEDULER_TABLE_ADDRESS_ARR */
uint32_t RDD_COMPLEX_SCHEDULER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1400,
	0x1400,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_COMPLEX_SCHEDULER_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1800,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_REPORTING_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_REPORTING_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1d00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_REPORTING_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_RUNNER_GLOBAL_REGISTERS_INIT_ADDRESS_ARR */
uint32_t RDD_RUNNER_GLOBAL_REGISTERS_INIT_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1da0,
	0x1c20,
	0xe20,
	0x160,
	0xa20,
	0x420,
	0xa20,
	0xa20,
};
/* <<<RDD_RUNNER_GLOBAL_REGISTERS_INIT_ADDRESS_ARR */


/* >>>RDD_DS_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1dc0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR */


/* >>>RDD_BASIC_SCHEDULER_TABLE_DS_ADDRESS_ARR */
uint32_t RDD_BASIC_SCHEDULER_TABLE_DS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x1e00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BASIC_SCHEDULER_TABLE_DS_ADDRESS_ARR */


/* >>>RDD_REPORTING_QUEUE_DESCRIPTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_REPORTING_QUEUE_DESCRIPTOR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2000,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_REPORTING_QUEUE_DESCRIPTOR_TABLE_ADDRESS_ARR */


/* >>>RDD_VLAN_TX_COUNTERS_ADDRESS_ARR */
uint32_t RDD_VLAN_TX_COUNTERS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2810,
	0x2b00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_VLAN_TX_COUNTERS_ADDRESS_ARR */


/* >>>RDD_DS_TM_CPU_TX_ABS_COUNTERS_ADDRESS_ARR */
uint32_t RDD_DS_TM_CPU_TX_ABS_COUNTERS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2c18,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_CPU_TX_ABS_COUNTERS_ADDRESS_ARR */


/* >>>RDD_DS_TM_BBH_TX_WAKE_UP_DATA_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_BBH_TX_WAKE_UP_DATA_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2c98,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_BBH_TX_WAKE_UP_DATA_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_SCHEDULING_FLUSH_VECTOR_ADDRESS_ARR */
uint32_t RDD_DS_TM_SCHEDULING_FLUSH_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2ca0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_SCHEDULING_FLUSH_VECTOR_ADDRESS_ARR */


/* >>>RDD_GHOST_REPORTING_GLOBAL_CFG_ADDRESS_ARR */
uint32_t RDD_GHOST_REPORTING_GLOBAL_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2cb4,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_GHOST_REPORTING_GLOBAL_CFG_ADDRESS_ARR */


/* >>>RDD_GENERAL_QUEUE_DYNAMIC_MNG_TABLE_ADDRESS_ARR */
uint32_t RDD_GENERAL_QUEUE_DYNAMIC_MNG_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2cb8,
	0x2f38,
	0xe08,
	0x2208,
	0xa08,
	0x2688,
	0xa08,
	0xa08,
};
/* <<<RDD_GENERAL_QUEUE_DYNAMIC_MNG_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2cc0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR */


/* >>>RDD_BUDGET_ALLOCATION_TIMER_VALUE_ADDRESS_ARR */
uint32_t RDD_BUDGET_ALLOCATION_TIMER_VALUE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2ce2,
	0x33dc,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BUDGET_ALLOCATION_TIMER_VALUE_ADDRESS_ARR */


/* >>>RDD_ZERO_VALUE_ADDRESS_ARR */
uint32_t RDD_ZERO_VALUE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2ce4,
	0x1db4,
	0x22e4,
	0x263c,
	0xedc,
	0x2a64,
	0xee4,
	0xee4,
};
/* <<<RDD_ZERO_VALUE_ADDRESS_ARR */


/* >>>RDD_MIRRORING_SCRATCH_ADDRESS_ARR */
uint32_t RDD_MIRRORING_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2ce8,
	0x39b8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_MIRRORING_SCRATCH_ADDRESS_ARR */


/* >>>RDD_XGPON_REPORT_TABLE_ADDRESS_ARR */
uint32_t RDD_XGPON_REPORT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2cf0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_XGPON_REPORT_TABLE_ADDRESS_ARR */


/* >>>RDD_NATC_TBL_CFG_ADDRESS_ARR */
uint32_t RDD_NATC_TBL_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2d00,
	0x3d00,
	0x2300,
	0x2700,
	0xf00,
	0x2b00,
	0xf00,
	0xf00,
};
/* <<<RDD_NATC_TBL_CFG_ADDRESS_ARR */


/* >>>RDD_REGISTERS_BUFFER_ADDRESS_ARR */
uint32_t RDD_REGISTERS_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2d48,
	0x3938,
	0x2208,
	0x2680,
	0x2380,
	0x2608,
	0xe08,
	0xe08,
};
/* <<<RDD_REGISTERS_BUFFER_ADDRESS_ARR */


/* >>>RDD_REPORT_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR */
uint32_t RDD_REPORT_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2dc8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_REPORT_BBH_TX_QUEUE_ID_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2dd0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_ONE_VALUE_ADDRESS_ARR */
uint32_t RDD_ONE_VALUE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2ddc,
	0x2f34,
	0x27a4,
	0x2e3c,
	0xeec,
	0x2a7c,
	0xfec,
	0xfec,
};
/* <<<RDD_ONE_VALUE_ADDRESS_ARR */


/* >>>RDD_DS_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR */
uint32_t RDD_DS_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2de0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR */


/* >>>RDD_DS_TM_BB_DESTINATION_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_BB_DESTINATION_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2df4,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_BB_DESTINATION_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_SCHEDULING_GLOBAL_FLUSH_CFG_ADDRESS_ARR */
uint32_t RDD_DS_TM_SCHEDULING_GLOBAL_FLUSH_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2df6,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_SCHEDULING_GLOBAL_FLUSH_CFG_ADDRESS_ARR */


/* >>>RDD_SCHEDULING_FLUSH_GLOBAL_CFG_ADDRESS_ARR */
uint32_t RDD_SCHEDULING_FLUSH_GLOBAL_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2df7,
	0x39e9,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SCHEDULING_FLUSH_GLOBAL_CFG_ADDRESS_ARR */


/* >>>RDD_BBH_TX_EGRESS_REPORT_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_BBH_TX_EGRESS_REPORT_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2df8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BBH_TX_EGRESS_REPORT_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_REPORTING_QUEUE_ACCUMULATED_TABLE_ADDRESS_ARR */
uint32_t RDD_REPORTING_QUEUE_ACCUMULATED_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_REPORTING_QUEUE_ACCUMULATED_TABLE_ADDRESS_ARR */


/* >>>RDD_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e40,
	0x3dc0,
	INVALID_TABLE_ADDRESS,
	0x2fc0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR */
uint32_t RDD_DS_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e60,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR */


/* >>>RDD_TASK_IDX_ADDRESS_ARR */
uint32_t RDD_TASK_IDX_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e74,
	0x33fc,
	0x27e4,
	0x2ebc,
	0xefc,
	0x2aa4,
	0x23a4,
	0x23a4,
};
/* <<<RDD_TASK_IDX_ADDRESS_ARR */


/* >>>RDD_TM_VLAN_STATS_ENABLE_ADDRESS_ARR */
uint32_t RDD_TM_VLAN_STATS_ENABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e78,
	0x39ec,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TM_VLAN_STATS_ENABLE_ADDRESS_ARR */


/* >>>RDD_CORE_ID_TABLE_ADDRESS_ARR */
uint32_t RDD_CORE_ID_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e79,
	0x39ed,
	0x27e3,
	0x2ee4,
	0xfdd,
	0x2ae3,
	0xff7,
	0xff7,
};
/* <<<RDD_CORE_ID_TABLE_ADDRESS_ARR */


/* >>>RDD_TX_MIRRORING_CONFIGURATION_ADDRESS_ARR */
uint32_t RDD_TX_MIRRORING_CONFIGURATION_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e7a,
	0x39ee,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TX_MIRRORING_CONFIGURATION_ADDRESS_ARR */


/* >>>RDD_DS_TM_FLUSH_AGGREGATION_TASK_DISABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_FLUSH_AGGREGATION_TASK_DISABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e7c,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_FLUSH_AGGREGATION_TASK_DISABLE_ADDRESS_ARR */


/* >>>RDD_SRAM_DUMMY_STORE_ADDRESS_ARR */
uint32_t RDD_SRAM_DUMMY_STORE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e7d,
	0x39fd,
	0x27fe,
	0x2ee5,
	0xffe,
	0x2ae6,
	0xffd,
	0xffd,
};
/* <<<RDD_SRAM_DUMMY_STORE_ADDRESS_ARR */


/* >>>RDD_RATE_LIMIT_OVERHEAD_ADDRESS_ARR */
uint32_t RDD_RATE_LIMIT_OVERHEAD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e7e,
	0x39fe,
	0x27ff,
	0x2f26,
	0xfff,
	0x2ae7,
	0x23a2,
	0x23a2,
};
/* <<<RDD_RATE_LIMIT_OVERHEAD_ADDRESS_ARR */


/* >>>RDD_DS_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR */
uint32_t RDD_DS_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e7f,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR */


/* >>>RDD_GHOST_REPORTING_QUEUE_STATUS_BIT_VECTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_GHOST_REPORTING_QUEUE_STATUS_BIT_VECTOR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_GHOST_REPORTING_QUEUE_STATUS_BIT_VECTOR_TABLE_ADDRESS_ARR */


/* >>>RDD_BBH_TX_INGRESS_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_BBH_TX_INGRESS_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2e94,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BBH_TX_INGRESS_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_RATE_LIMITER_VALID_TABLE_DS_ADDRESS_ARR */
uint32_t RDD_RATE_LIMITER_VALID_TABLE_DS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2ea0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_RATE_LIMITER_VALID_TABLE_DS_ADDRESS_ARR */


/* >>>RDD_TX_MIRRORING_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_TX_MIRRORING_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2eb0,
	0x3af0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TX_MIRRORING_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_TM_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2ec0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_FPM_GLOBAL_CFG_ADDRESS_ARR */
uint32_t RDD_FPM_GLOBAL_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2ed0,
	0x3b60,
	0x29f0,
	0x2ff0,
	0x27f0,
	0x2af0,
	0xfe0,
	0xfe0,
};
/* <<<RDD_FPM_GLOBAL_CFG_ADDRESS_ARR */


/* >>>RDD_XGPON_REPORT_ZERO_SENT_TABLE_ADDRESS_ARR */
uint32_t RDD_XGPON_REPORT_ZERO_SENT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x2ee0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_XGPON_REPORT_ZERO_SENT_TABLE_ADDRESS_ARR */


/* >>>RDD_BASIC_RATE_LIMITER_TABLE_DS_ADDRESS_ARR */
uint32_t RDD_BASIC_RATE_LIMITER_TABLE_DS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x3000,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BASIC_RATE_LIMITER_TABLE_DS_ADDRESS_ARR */


/* >>>RDD_RUNNER_PROFILING_TRACE_BUFFER_ADDRESS_ARR */
uint32_t RDD_RUNNER_PROFILING_TRACE_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x3800,
	0x3000,
	0x2400,
	0x2800,
	0x2000,
	0x2c00,
	0x2000,
	0x2000,
};
/* <<<RDD_RUNNER_PROFILING_TRACE_BUFFER_ADDRESS_ARR */


/* >>>RDD_DS_TM_BBH_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_TM_BBH_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	0x3a00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_TM_BBH_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_SSID_STATS_TABLE_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_SSID_STATS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x1080,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_WLAN_MCAST_SSID_STATS_TABLE_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_COPY_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_COPY_SCRATCHPAD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x1200,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_WLAN_MCAST_COPY_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_US_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x1800,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_DHD_STATION_CTX_TABLE_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_DHD_STATION_CTX_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x1c40,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_WLAN_MCAST_DHD_STATION_CTX_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x1c80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_TM_FLOW_CNTR_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_TX_POST_FLOW_RING_BUFFER_ADDRESS_ARR */
uint32_t RDD_DHD_TX_POST_FLOW_RING_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x1d00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_TX_POST_FLOW_RING_BUFFER_ADDRESS_ARR */


/* >>>RDD_DHD_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x1d90,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_SCHEDULING_FLUSH_VECTOR_ADDRESS_ARR */
uint32_t RDD_US_TM_SCHEDULING_FLUSH_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x1da0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_SCHEDULING_FLUSH_VECTOR_ADDRESS_ARR */


/* >>>RDD_US_TM_BBH_TX_WAKE_UP_DATA_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_BBH_TX_WAKE_UP_DATA_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x1db8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_BBH_TX_WAKE_UP_DATA_TABLE_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_DFT_LIST_ENTRY_SCRATCH_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_DFT_LIST_ENTRY_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x1dc0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_WLAN_MCAST_DFT_LIST_ENTRY_SCRATCH_ADDRESS_ARR */


/* >>>RDD_BASIC_SCHEDULER_TABLE_US_ADDRESS_ARR */
uint32_t RDD_BASIC_SCHEDULER_TABLE_US_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x1e00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BASIC_SCHEDULER_TABLE_US_ADDRESS_ARR */


/* >>>RDD_BASIC_RATE_LIMITER_TABLE_US_ADDRESS_ARR */
uint32_t RDD_BASIC_RATE_LIMITER_TABLE_US_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2000,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BASIC_RATE_LIMITER_TABLE_US_ADDRESS_ARR */


/* >>>RDD_DHD_FLOW_RING_CACHE_CTX_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_FLOW_RING_CACHE_CTX_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2800,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_FLOW_RING_CACHE_CTX_TABLE_ADDRESS_ARR */


/* >>>RDD_BBH_TX_EPON_WAKE_UP_DATA_TABLE_ADDRESS_ARR */
uint32_t RDD_BBH_TX_EPON_WAKE_UP_DATA_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2f08,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BBH_TX_EPON_WAKE_UP_DATA_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_HW_CFG_ADDRESS_ARR */
uint32_t RDD_DHD_HW_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2f10,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xe30,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_HW_CFG_ADDRESS_ARR */


/* >>>RDD_US_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR */
uint32_t RDD_US_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2f20,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_SCHEDULING_QUEUE_AGING_VECTOR_ADDRESS_ARR */


/* >>>RDD_US_TM_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2f40,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_BBH_TX_EGRESS_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */
uint32_t RDD_DHD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2f68,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x27b0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */


/* >>>RDD_OVERALL_RATE_LIMITER_TABLE_ADDRESS_ARR */
uint32_t RDD_OVERALL_RATE_LIMITER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2f70,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_OVERALL_RATE_LIMITER_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_BACKUP_INDEX_CACHE_ADDRESS_ARR */
uint32_t RDD_DHD_BACKUP_INDEX_CACHE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2f80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_BACKUP_INDEX_CACHE_ADDRESS_ARR */


/* >>>RDD_US_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR */
uint32_t RDD_US_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2fe0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_SCHEDULING_AGGREGATION_CONTEXT_VECTOR_ADDRESS_ARR */


/* >>>RDD_US_TM_BBH_TX_FIFO_BYTES_USED_ADDRESS_ARR */
uint32_t RDD_US_TM_BBH_TX_FIFO_BYTES_USED_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2ff4,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_BBH_TX_FIFO_BYTES_USED_ADDRESS_ARR */


/* >>>RDD_DHD_BACKUP_BASE_ADDR_ADDRESS_ARR */
uint32_t RDD_DHD_BACKUP_BASE_ADDR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x2ff8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_BACKUP_BASE_ADDR_ADDRESS_ARR */


/* >>>RDD_DHD_BACKUP_INFO_CACHE_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_BACKUP_INFO_CACHE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3200,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_BACKUP_INFO_CACHE_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_L2_HEADER_ADDRESS_ARR */
uint32_t RDD_DHD_L2_HEADER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3380,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_L2_HEADER_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_DFT_ADDR_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_DFT_ADDR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x33c8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_WLAN_MCAST_DFT_ADDR_ADDRESS_ARR */


/* >>>RDD_US_TM_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x33d0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_FLUSH_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_BB_DESTINATION_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_BB_DESTINATION_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x33de,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_BB_DESTINATION_TABLE_ADDRESS_ARR */


/* >>>RDD_RATE_LIMITER_VALID_TABLE_US_ADDRESS_ARR */
uint32_t RDD_RATE_LIMITER_VALID_TABLE_US_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x33e0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_RATE_LIMITER_VALID_TABLE_US_ADDRESS_ARR */


/* >>>RDD_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x33f0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_DHD_STATION_TABLE_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_DHD_STATION_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3400,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_WLAN_MCAST_DHD_STATION_TABLE_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_SSID_MAC_ADDRESS_TABLE_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_SSID_MAC_ADDRESS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3600,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_WLAN_MCAST_SSID_MAC_ADDRESS_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_CPU_TX_ABS_COUNTERS_ADDRESS_ARR */
uint32_t RDD_US_TM_CPU_TX_ABS_COUNTERS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3780,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_CPU_TX_ABS_COUNTERS_ADDRESS_ARR */


/* >>>RDD_DHD_POST_COMMON_RADIO_DATA_ADDRESS_ARR */
uint32_t RDD_DHD_POST_COMMON_RADIO_DATA_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3800,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_POST_COMMON_RADIO_DATA_ADDRESS_ARR */


/* >>>RDD_BBH_TX_EPON_INGRESS_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_BBH_TX_EPON_INGRESS_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x39c0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BBH_TX_EPON_INGRESS_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_SCHEDULING_GLOBAL_FLUSH_CFG_ADDRESS_ARR */
uint32_t RDD_US_TM_SCHEDULING_GLOBAL_FLUSH_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x39e8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_SCHEDULING_GLOBAL_FLUSH_CFG_ADDRESS_ARR */


/* >>>RDD_BBH_TX_US_FIFO_BYTES_THRESHOLD_ADDRESS_ARR */
uint32_t RDD_BBH_TX_US_FIFO_BYTES_THRESHOLD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x39ea,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BBH_TX_US_FIFO_BYTES_THRESHOLD_ADDRESS_ARR */


/* >>>RDD_DHD_MCAST_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_MCAST_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x39f0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_MCAST_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_FLUSH_AGGREGATION_TASK_DISABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_FLUSH_AGGREGATION_TASK_DISABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x39fc,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_FLUSH_AGGREGATION_TASK_DISABLE_ADDRESS_ARR */


/* >>>RDD_BBH_TX_FIFO_SIZE_ADDRESS_ARR */
uint32_t RDD_BBH_TX_FIFO_SIZE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x39ff,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BBH_TX_FIFO_SIZE_ADDRESS_ARR */


/* >>>RDD_DHD_TX_POST_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_TX_POST_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3a00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_TX_POST_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_SCRATCHPAD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3ac0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_WLAN_MCAST_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_US_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR */
uint32_t RDD_US_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3ae8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_FIRST_QUEUE_MAPPING_ADDRESS_ARR */


/* >>>RDD_DHD_FLOW_RING_CACHE_LKP_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_FLOW_RING_CACHE_LKP_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3b00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_FLOW_RING_CACHE_LKP_TABLE_ADDRESS_ARR */


/* >>>RDD_WLAN_MCAST_DFT_LIST_SIZE_ADDRESS_ARR */
uint32_t RDD_WLAN_MCAST_DFT_LIST_SIZE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3b80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_WLAN_MCAST_DFT_LIST_SIZE_ADDRESS_ARR */


/* >>>RDD_US_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3bc0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_TM_ACTION_PTR_TABLE_ADDRESS_ARR */


/* >>>RDD_US_TM_BBH_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_US_TM_BBH_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3c00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_TM_BBH_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_BBH_TX_EPON_EGRESS_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_BBH_TX_EPON_EGRESS_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3cc0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_BBH_TX_EPON_EGRESS_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3d80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2780,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */


/* >>>RDD_EPON_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_EPON_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3e00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_EPON_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_TX_POST_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_TX_POST_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3e40,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_TX_POST_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_MCAST_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_MCAST_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3e80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_MCAST_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_MCAST_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_MCAST_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3ec0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_MCAST_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_DOORBELL_TX_POST_VALUE_ADDRESS_ARR */
uint32_t RDD_DHD_DOORBELL_TX_POST_VALUE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	0x3ee0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_DOORBELL_TX_POST_VALUE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_CPU_TX_SCRATCHPAD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_RX_FLOW_TABLE_ADDRESS_ARR */
uint32_t RDD_RX_FLOW_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x400,
	0x800,
	0x0,
	0xc00,
	0x0,
	0x0,
};
/* <<<RDD_RX_FLOW_TABLE_ADDRESS_ARR */


/* >>>RDD_VPORT_CFG_TABLE_ADDRESS_ARR */
uint32_t RDD_VPORT_CFG_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x680,
	0x180,
	0x280,
	0x480,
	0x280,
	0x280,
};
/* <<<RDD_VPORT_CFG_TABLE_ADDRESS_ARR */


/* >>>RDD_DSCP_TO_PBITS_MAP_TABLE_ADDRESS_ARR */
uint32_t RDD_DSCP_TO_PBITS_MAP_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x700,
	0x600,
	0x300,
	0x500,
	0x300,
	0x300,
};
/* <<<RDD_DSCP_TO_PBITS_MAP_TABLE_ADDRESS_ARR */


/* >>>RDD_TCAM_IC_CMD_TABLE_ADDRESS_ARR */
uint32_t RDD_TCAM_IC_CMD_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x800,
	0xc00,
	0x400,
	0x2000,
	0x400,
	0x400,
};
/* <<<RDD_TCAM_IC_CMD_TABLE_ADDRESS_ARR */


/* >>>RDD_GLOBAL_DSCP_TO_PBITS_TABLE_ADDRESS_ARR */
uint32_t RDD_GLOBAL_DSCP_TO_PBITS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xa40,
	0x7c0,
	0x640,
	0x440,
	0x640,
	0x640,
};
/* <<<RDD_GLOBAL_DSCP_TO_PBITS_TABLE_ADDRESS_ARR */


/* >>>RDD_PBIT_TO_GEM_TABLE_ADDRESS_ARR */
uint32_t RDD_PBIT_TO_GEM_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xa80,
	0x380,
	0x680,
	0x780,
	0x680,
	0x680,
};
/* <<<RDD_PBIT_TO_GEM_TABLE_ADDRESS_ARR */


/* >>>RDD_INGRESS_FILTER_PROFILE_TABLE_ADDRESS_ARR */
uint32_t RDD_INGRESS_FILTER_PROFILE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xb00,
	0xf00,
	0x700,
	0x2300,
	0x700,
	0x700,
};
/* <<<RDD_INGRESS_FILTER_PROFILE_TABLE_ADDRESS_ARR */


/* >>>RDD_LAYER2_HEADER_COPY_MAPPING_TABLE_ADDRESS_ARR */
uint32_t RDD_LAYER2_HEADER_COPY_MAPPING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xb80,
	0xb80,
	0x780,
	0xe80,
	0x780,
	0x780,
};
/* <<<RDD_LAYER2_HEADER_COPY_MAPPING_TABLE_ADDRESS_ARR */


/* >>>RDD_IPTV_CONFIGURATION_TABLE_ADDRESS_ARR */
uint32_t RDD_IPTV_CONFIGURATION_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xbf8,
	0xbf8,
	0x7f8,
	0xef8,
	0x7f8,
	0x7f8,
};
/* <<<RDD_IPTV_CONFIGURATION_TABLE_ADDRESS_ARR */


/* >>>RDD_TC_TO_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_TC_TO_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xc00,
	0x2000,
	0x800,
	0x2400,
	0x800,
	0x800,
};
/* <<<RDD_TC_TO_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_VPORT_TO_DSCP_TO_PBITS_TABLE_ADDRESS_ARR */
uint32_t RDD_VPORT_TO_DSCP_TO_PBITS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xe10,
	0xef0,
	0xa10,
	0x22d0,
	0xa10,
	0xa10,
};
/* <<<RDD_VPORT_TO_DSCP_TO_PBITS_TABLE_ADDRESS_ARR */


/* >>>RDD_DUAL_STACK_LITE_TABLE_ADDRESS_ARR */
uint32_t RDD_DUAL_STACK_LITE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xe40,
	0xe40,
	0xa40,
	0x2240,
	0xa40,
	0xa40,
};
/* <<<RDD_DUAL_STACK_LITE_TABLE_ADDRESS_ARR */


/* >>>RDD_POLICER_PARAMS_TABLE_ADDRESS_ARR */
uint32_t RDD_POLICER_PARAMS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xe80,
	0xf80,
	0xe80,
	0x2280,
	0xa80,
	0xa80,
};
/* <<<RDD_POLICER_PARAMS_TABLE_ADDRESS_ARR */


/* >>>RDD_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR */
uint32_t RDD_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xed0,
	0xfd0,
	0xe10,
	0x2690,
	0xad0,
	0xad0,
};
/* <<<RDD_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR */


/* >>>RDD_TCAM_IC_HANDLER_TABLE_ADDRESS_ARR */
uint32_t RDD_TCAM_IC_HANDLER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xee0,
	0x23e0,
	0xae0,
	0x22e0,
	0xae0,
	0xae0,
};
/* <<<RDD_TCAM_IC_HANDLER_TABLE_ADDRESS_ARR */


/* >>>RDD_EMAC_FLOW_CTRL_ADDRESS_ARR */
uint32_t RDD_EMAC_FLOW_CTRL_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xf00,
	0x2300,
	0xb00,
	0x2700,
	0xb00,
	0xb00,
};
/* <<<RDD_EMAC_FLOW_CTRL_ADDRESS_ARR */


/* >>>RDD_NATC_COUNTERS_GENERIC_CONTEXT_ADDRESS_ARR */
uint32_t RDD_NATC_COUNTERS_GENERIC_CONTEXT_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xf60,
	0x2360,
	0xf48,
	0x2380,
	0xb60,
	0xb60,
};
/* <<<RDD_NATC_COUNTERS_GENERIC_CONTEXT_ADDRESS_ARR */


/* >>>RDD_SPDSVC_ANALYZER_PARAMS_TABLE_ADDRESS_ARR */
uint32_t RDD_SPDSVC_ANALYZER_PARAMS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xfe0,
	0x2620,
	0xb60,
	0x26a0,
	0xbe0,
	0xbe0,
};
/* <<<RDD_SPDSVC_ANALYZER_PARAMS_TABLE_ADDRESS_ARR */


/* >>>RDD_INGRESS_PACKET_BASED_MAPPING_ADDRESS_ARR */
uint32_t RDD_INGRESS_PACKET_BASED_MAPPING_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xffc,
	0xeec,
	0xb7c,
	0x26bc,
	0xbfc,
	0xbfc,
};
/* <<<RDD_INGRESS_PACKET_BASED_MAPPING_ADDRESS_ARR */


/* >>>RDD_DS_PACKET_BUFFER_ADDRESS_ARR */
uint32_t RDD_DS_PACKET_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x1000,
	0x1000,
	0x1000,
	0x1000,
	0x1000,
	0x1000,
};
/* <<<RDD_DS_PACKET_BUFFER_ADDRESS_ARR */


/* >>>RDD_PBIT_TO_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_PBIT_TO_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2000,
	0x2400,
	0xc00,
	0x2800,
	0xc00,
	0xc00,
};
/* <<<RDD_PBIT_TO_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_PROCESSING_QUEUE_DYNAMIC_MNG_TABLE_ADDRESS_ARR */
uint32_t RDD_PROCESSING_QUEUE_DYNAMIC_MNG_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2288,
	0x2608,
	0xbf8,
	0x27f8,
	0xe88,
	0xe88,
};
/* <<<RDD_PROCESSING_QUEUE_DYNAMIC_MNG_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2290,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_FPM_POOL_NUMBER_MAPPING_TABLE_ADDRESS_ARR */


/* >>>RDD_BRIDGE_CFG_TABLE_ADDRESS_ARR */
uint32_t RDD_BRIDGE_CFG_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x22a0,
	0x27e0,
	0xbe0,
	0x27e0,
	0xea0,
	0xea0,
};
/* <<<RDD_BRIDGE_CFG_TABLE_ADDRESS_ARR */


/* >>>RDD_EMAC_FLOW_CTRL_CTR_REP_ADDRESS_ARR */
uint32_t RDD_EMAC_FLOW_CTRL_CTR_REP_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x22b8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_EMAC_FLOW_CTRL_CTR_REP_ADDRESS_ARR */


/* >>>RDD_FLOW_BASED_ACTION_PTR_TABLE_ADDRESS_ARR */
uint32_t RDD_FLOW_BASED_ACTION_PTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x22c0,
	0x2ec0,
	0x2740,
	0x2a40,
	0xec0,
	0xec0,
};
/* <<<RDD_FLOW_BASED_ACTION_PTR_TABLE_ADDRESS_ARR */


/* >>>RDD_BRIDGE_LAN_MAC_ADDRESS_ARR */
uint32_t RDD_BRIDGE_LAN_MAC_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x22e8,
	0x2748,
	0xe08,
	0x2a08,
	0xeb8,
	0xeb8,
};
/* <<<RDD_BRIDGE_LAN_MAC_ADDRESS_ARR */


/* >>>RDD_FPM_REPLY_ADDRESS_ARR */
uint32_t RDD_FPM_REPLY_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x22f0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_FPM_REPLY_ADDRESS_ARR */


/* >>>RDD_RX_FLOW_CONTEXT_DDR_ADDR_ADDRESS_ARR */
uint32_t RDD_RX_FLOW_CONTEXT_DDR_ADDR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2348,
	0x27f8,
	0xfc8,
	0x2a68,
	0xee8,
	0xee8,
};
/* <<<RDD_RX_FLOW_CONTEXT_DDR_ADDR_ADDRESS_ARR */


/* >>>RDD_LOOPBACK_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_LOOPBACK_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2350,
	0x2210,
	0xe20,
	0x2a10,
	0xe90,
	0xe90,
};
/* <<<RDD_LOOPBACK_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_TCAM_IC_CFG_TABLE_ADDRESS_ARR */
uint32_t RDD_TCAM_IC_CFG_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2360,
	0x2760,
	0x2560,
	0x2760,
	0xf60,
	0xf60,
};
/* <<<RDD_TCAM_IC_CFG_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x23e0,
	0x2610,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR */


/* >>>RDD_INGRESS_FILTER_L2_REASON_TABLE_ADDRESS_ARR */
uint32_t RDD_INGRESS_FILTER_L2_REASON_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x23f0,
	0x2bf0,
	0xe70,
	0x2a30,
	0xef0,
	0xef0,
};
/* <<<RDD_INGRESS_FILTER_L2_REASON_TABLE_ADDRESS_ARR */


/* >>>RDD_LAYER2_GRE_TUNNEL_TABLE_ADDRESS_ARR */
uint32_t RDD_LAYER2_GRE_TUNNEL_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2600,
	0x200,
	0x2200,
	0x600,
	0x2200,
	0x2200,
};
/* <<<RDD_LAYER2_GRE_TUNNEL_TABLE_ADDRESS_ARR */


/* >>>RDD_QUEUE_THRESHOLD_VECTOR_ADDRESS_ARR */
uint32_t RDD_QUEUE_THRESHOLD_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2780,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_QUEUE_THRESHOLD_VECTOR_ADDRESS_ARR */


/* >>>RDD_NULL_BUFFER_ADDRESS_ARR */
uint32_t RDD_NULL_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x27a8,
	0x2bb8,
	0x2768,
	0x2aa8,
	0xf48,
	0xf48,
};
/* <<<RDD_NULL_BUFFER_ADDRESS_ARR */


/* >>>RDD_CPU_TX_EGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_EGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x27b0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_EGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_FLOW_CTRL_TIMER_VALUE_ADDRESS_ARR */
uint32_t RDD_FLOW_CTRL_TIMER_VALUE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x27bc,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_FLOW_CTRL_TIMER_VALUE_ADDRESS_ARR */


/* >>>RDD_EMAC_FLOW_CTRL_VECTOR_ADDRESS_ARR */
uint32_t RDD_EMAC_FLOW_CTRL_VECTOR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x27be,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_EMAC_FLOW_CTRL_VECTOR_ADDRESS_ARR */


/* >>>RDD_FORCE_DSCP_ADDRESS_ARR */
uint32_t RDD_FORCE_DSCP_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x27bf,
	0x2b7f,
	0xfdc,
	0x2ae2,
	0xff6,
	0xff6,
};
/* <<<RDD_FORCE_DSCP_ADDRESS_ARR */


/* >>>RDD_RULE_BASED_ACTION_PTR_TABLE_ADDRESS_ARR */
uint32_t RDD_RULE_BASED_ACTION_PTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x27c0,
	0x2f00,
	0x27c0,
	0x2a80,
	0x2380,
	0x2380,
};
/* <<<RDD_RULE_BASED_ACTION_PTR_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_VLAN_STATS_ENABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_VLAN_STATS_ENABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x27e2,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_VLAN_STATS_ENABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x27e8,
	0x2e68,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */


/* >>>RDD_CPU_TX_INGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_INGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x27f0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_INGRESS_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_RX_MIRRORING_CONFIGURATION_ADDRESS_ARR */
uint32_t RDD_RX_MIRRORING_CONFIGURATION_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x27fc,
	0x2f24,
	0xffc,
	0x2ae4,
	0xffe,
	0xffe,
};
/* <<<RDD_RX_MIRRORING_CONFIGURATION_ADDRESS_ARR */


/* >>>RDD_TX_FLOW_TABLE_ADDRESS_ARR */
uint32_t RDD_TX_FLOW_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2800,
	0x0,
	0x2600,
	0x2e00,
	0x2400,
	0x2400,
};
/* <<<RDD_TX_FLOW_TABLE_ADDRESS_ARR */


/* >>>RDD_IPTV_ACTION_PTR_TABLE_ADDRESS_ARR */
uint32_t RDD_IPTV_ACTION_PTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2940,
	0x2f40,
	0x2800,
	0x2ac0,
	0x23c0,
	0x23c0,
};
/* <<<RDD_IPTV_ACTION_PTR_TABLE_ADDRESS_ARR */


/* >>>RDD_INGRESS_QOS_DONT_DROP_RATIO_ADDRESS_ARR */
uint32_t RDD_INGRESS_QOS_DONT_DROP_RATIO_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2962,
	0x2f27,
	0x255c,
	0x2aee,
	0x23a3,
	0x23a3,
};
/* <<<RDD_INGRESS_QOS_DONT_DROP_RATIO_ADDRESS_ARR */


/* >>>RDD_INGRESS_QOS_WAN_UNTAGGED_PRIORITY_ADDRESS_ARR */
uint32_t RDD_INGRESS_QOS_WAN_UNTAGGED_PRIORITY_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2963,
	0x2f3e,
	0x255d,
	0x2aef,
	0x23e2,
	0x23e2,
};
/* <<<RDD_INGRESS_QOS_WAN_UNTAGGED_PRIORITY_ADDRESS_ARR */


/* >>>RDD_IC_MCAST_ENABLE_ADDRESS_ARR */
uint32_t RDD_IC_MCAST_ENABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2964,
	0x2f62,
	0x255e,
	0x2afc,
	0x23e3,
	0x23e3,
};
/* <<<RDD_IC_MCAST_ENABLE_ADDRESS_ARR */


/* >>>RDD_ECN_IPV6_REMARK_TABLE_ADDRESS_ARR */
uint32_t RDD_ECN_IPV6_REMARK_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2965,
	0x2f63,
	0x255f,
	0x2afd,
	0x23e4,
	0x23e4,
};
/* <<<RDD_ECN_IPV6_REMARK_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_REDIRECT_MODE_ADDRESS_ARR */
uint32_t RDD_CPU_REDIRECT_MODE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2966,
	0x2f64,
	0x25ec,
	0x2afe,
	0x23e5,
	0x23e5,
};
/* <<<RDD_CPU_REDIRECT_MODE_ADDRESS_ARR */


/* >>>RDD_IPTV_CLASSIFICATION_CFG_TABLE_ADDRESS_ARR */
uint32_t RDD_IPTV_CLASSIFICATION_CFG_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2967,
	0x2f65,
	0x25ed,
	0x2b4d,
	0x23e6,
	0x23e6,
};
/* <<<RDD_IPTV_CLASSIFICATION_CFG_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */
uint32_t RDD_CPU_RX_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2968,
	0x2ea8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_INTERRUPT_ID_DDR_ADDR_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2970,
	0x2ef0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */


/* >>>RDD_VLAN_ACTION_GPE_HANDLER_PTR_TABLE_ADDRESS_ARR */
uint32_t RDD_VLAN_ACTION_GPE_HANDLER_PTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2980,
	0x2f80,
	0x2840,
	0x2b80,
	0x2540,
	0x2540,
};
/* <<<RDD_VLAN_ACTION_GPE_HANDLER_PTR_TABLE_ADDRESS_ARR */


/* >>>RDD_INGRESS_FILTER_1588_CFG_ADDRESS_ARR */
uint32_t RDD_INGRESS_FILTER_1588_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x29a2,
	0x2f66,
	0x25ee,
	0x2b4e,
	0x23e7,
	0x23e7,
};
/* <<<RDD_INGRESS_FILTER_1588_CFG_ADDRESS_ARR */


/* >>>RDD_RX_MIRRORING_DIRECT_ENABLE_ADDRESS_ARR */
uint32_t RDD_RX_MIRRORING_DIRECT_ENABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x29a3,
	0x2f67,
	0x25ef,
	0x2b4f,
	0x23ef,
	0x23ef,
};
/* <<<RDD_RX_MIRRORING_DIRECT_ENABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_RING_INDEX_DDR_ADDR_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_RING_INDEX_DDR_ADDR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x29a8,
	0x2f28,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_RING_INDEX_DDR_ADDR_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_FPM_THRESHOLDS_ADDRESS_ARR */
uint32_t RDD_DHD_FPM_THRESHOLDS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x29b8,
	0x2f38,
	0x27b8,
	0x2ae8,
	0xff0,
	0xff0,
};
/* <<<RDD_DHD_FPM_THRESHOLDS_ADDRESS_ARR */


/* >>>RDD_CPU_TX_EGRESS_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_EGRESS_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x29c0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_EGRESS_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_FEED_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_FEED_RING_DESCRIPTOR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x29e0,
	0x2fb0,
	0x2770,
	0x2ab0,
	0xf50,
	0xf50,
};
/* <<<RDD_CPU_FEED_RING_DESCRIPTOR_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_SRAM_PD_FIFO_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_SRAM_PD_FIFO_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2a00,
	0x2a00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_SRAM_PD_FIFO_ADDRESS_ARR */


/* >>>RDD_CPU_TX_INGRESS_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_INGRESS_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_INGRESS_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_SYSTEM_CONFIGURATION_ADDRESS_ARR */
uint32_t RDD_SYSTEM_CONFIGURATION_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b20,
	0x2f68,
	0x27e8,
	0x2b48,
	0xff8,
	0xff8,
};
/* <<<RDD_SYSTEM_CONFIGURATION_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b28,
	0x2fa8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_TUNNELS_PARSING_CFG_ADDRESS_ARR */
uint32_t RDD_TUNNELS_PARSING_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b30,
	0x3128,
	0x2828,
	0x2b50,
	0x23a8,
	0x23a8,
};
/* <<<RDD_TUNNELS_PARSING_CFG_ADDRESS_ARR */


/* >>>RDD_IPTV_CFG_TABLE_ADDRESS_ARR */
uint32_t RDD_IPTV_CFG_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b38,
	0x3130,
	0x2830,
	0x2b58,
	0x23b0,
	0x23b0,
};
/* <<<RDD_IPTV_CFG_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_TX_EGRESS_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_EGRESS_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b40,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_EGRESS_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_IPTV_DDR_CTX_TABLE_ADDRESS_ADDRESS_ARR */
uint32_t RDD_IPTV_DDR_CTX_TABLE_ADDRESS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b60,
	0x3138,
	0x2838,
	0x2b60,
	0x23b8,
	0x23b8,
};
/* <<<RDD_IPTV_DDR_CTX_TABLE_ADDRESS_ADDRESS_ARR */


/* >>>RDD_NAT_CACHE_CFG_ADDRESS_ARR */
uint32_t RDD_NAT_CACHE_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b68,
	0x3160,
	0x2868,
	0x2b68,
	0x23e8,
	0x23e8,
};
/* <<<RDD_NAT_CACHE_CFG_ADDRESS_ARR */


/* >>>RDD_NAT_CACHE_KEY0_MASK_ADDRESS_ARR */
uint32_t RDD_NAT_CACHE_KEY0_MASK_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b70,
	0x3168,
	0x2870,
	0x2b70,
	0x23f0,
	0x23f0,
};
/* <<<RDD_NAT_CACHE_KEY0_MASK_ADDRESS_ARR */


/* >>>RDD_NATC_L2_VLAN_KEY_MASK_ADDRESS_ARR */
uint32_t RDD_NATC_L2_VLAN_KEY_MASK_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b78,
	0x3170,
	0x2878,
	0x2b78,
	0x23f8,
	0x23f8,
};
/* <<<RDD_NATC_L2_VLAN_KEY_MASK_ADDRESS_ARR */


/* >>>RDD_CPU_TX_INGRESS_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_TX_INGRESS_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_TX_INGRESS_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_INGRESS_FILTER_CFG_ADDRESS_ARR */
uint32_t RDD_INGRESS_FILTER_CFG_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2ba0,
	0x3178,
	0x28a0,
	0x2ba8,
	0x2568,
	0x2568,
};
/* <<<RDD_INGRESS_FILTER_CFG_ADDRESS_ARR */


/* >>>RDD_NATC_L2_TOS_MASK_ADDRESS_ARR */
uint32_t RDD_NATC_L2_TOS_MASK_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2ba8,
	0x31a0,
	0x28a8,
	0x2bb0,
	0x2570,
	0x2570,
};
/* <<<RDD_NATC_L2_TOS_MASK_ADDRESS_ARR */


/* >>>RDD_VPORT_CFG_EX_TABLE_ADDRESS_ARR */
uint32_t RDD_VPORT_CFG_EX_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2bc0,
	0x3200,
	0x2880,
	0x2f40,
	0x2580,
	0x2580,
};
/* <<<RDD_VPORT_CFG_EX_TABLE_ADDRESS_ARR */


/* >>>RDD_EMAC_FLOW_CTRL_BUDGET_ADDRESS_ARR */
uint32_t RDD_EMAC_FLOW_CTRL_BUDGET_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2c00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_EMAC_FLOW_CTRL_BUDGET_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_INTERRUPT_SCRATCH_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_INTERRUPT_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2c80,
	0x3380,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_INTERRUPT_SCRATCH_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_SHADOW_RD_IDX_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_SHADOW_RD_IDX_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2d00,
	0x3400,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_SHADOW_RD_IDX_ADDRESS_ARR */


/* >>>RDD_CPU_RECYCLE_SHADOW_WR_IDX_ADDRESS_ARR */
uint32_t RDD_CPU_RECYCLE_SHADOW_WR_IDX_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2d80,
	0x3480,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RECYCLE_SHADOW_WR_IDX_ADDRESS_ARR */


/* >>>RDD_DIRECT_PROCESSING_PD_TABLE_ADDRESS_ARR */
uint32_t RDD_DIRECT_PROCESSING_PD_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x140,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DIRECT_PROCESSING_PD_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_CPU_RX_SCRATCHPAD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x400,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_CPU_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x700,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RING_INTERRUPT_COUNTER_TABLE_ADDRESS_ARR */


/* >>>RDD_DIRECT_PROCESSING_EPON_CONTROL_SCRATCH_ADDRESS_ARR */
uint32_t RDD_DIRECT_PROCESSING_EPON_CONTROL_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x790,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DIRECT_PROCESSING_EPON_CONTROL_SCRATCH_ADDRESS_ARR */


/* >>>RDD_VPORT_TO_FLOW_IDX_ADDRESS_ARR */
uint32_t RDD_VPORT_TO_FLOW_IDX_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x7a0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_VPORT_TO_FLOW_IDX_ADDRESS_ARR */


/* >>>RDD_DS_CPU_RX_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_CPU_RX_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xa80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_CPU_RX_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_US_CPU_RX_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_US_CPU_RX_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xb00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_CPU_RX_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_CSO_CONTEXT_TABLE_ADDRESS_ARR */
uint32_t RDD_CSO_CONTEXT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xe80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CSO_CONTEXT_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_FEED_RING_RSV_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_FEED_RING_RSV_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xfe0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_FEED_RING_RSV_TABLE_ADDRESS_ARR */


/* >>>RDD_IPV4_HOST_ADDRESS_TABLE_ADDRESS_ARR */
uint32_t RDD_IPV4_HOST_ADDRESS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2220,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_IPV4_HOST_ADDRESS_TABLE_ADDRESS_ARR */


/* >>>RDD_DS_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_DS_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2240,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DS_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_COPY_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RX_COPY_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2280,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_COPY_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_US_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_US_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x22c0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_US_CPU_REASON_TO_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_IPV6_HOST_ADDRESS_CRC_TABLE_ADDRESS_ARR */
uint32_t RDD_IPV6_HOST_ADDRESS_CRC_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2640,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_IPV6_HOST_ADDRESS_CRC_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_PSRAM_GET_NEXT_SCRATCHPAD_ADDRESS_ARR */
uint32_t RDD_CPU_RX_PSRAM_GET_NEXT_SCRATCHPAD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2750,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_PSRAM_GET_NEXT_SCRATCHPAD_ADDRESS_ARR */


/* >>>RDD_TCPSPDTEST_ENGINE_REF_PKT_HDR_TABLE_ADDRESS_ARR */
uint32_t RDD_TCPSPDTEST_ENGINE_REF_PKT_HDR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TCPSPDTEST_ENGINE_REF_PKT_HDR_TABLE_ADDRESS_ARR */


/* >>>RDD_DIRECT_PROCESSING_WAN_VIQ_EXCLUSIVE_ADDRESS_ARR */
uint32_t RDD_DIRECT_PROCESSING_WAN_VIQ_EXCLUSIVE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b7e,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DIRECT_PROCESSING_WAN_VIQ_EXCLUSIVE_ADDRESS_ARR */


/* >>>RDD_TCPSPDTEST_ENGINE_TCB_TABLE_ADDRESS_ARR */
uint32_t RDD_TCPSPDTEST_ENGINE_TCB_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2b80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TCPSPDTEST_ENGINE_TCB_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_REASON_AND_VPORT_TO_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_REASON_AND_VPORT_TO_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2bc0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_REASON_AND_VPORT_TO_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_TCPSPDTEST_ENGINE_PKT_DROP_TABLE_ADDRESS_ARR */
uint32_t RDD_TCPSPDTEST_ENGINE_PKT_DROP_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2c00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TCPSPDTEST_ENGINE_PKT_DROP_TABLE_ADDRESS_ARR */


/* >>>RDD_SCRATCH_ADDRESS_ARR */
uint32_t RDD_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2e08,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SCRATCH_ADDRESS_ARR */


/* >>>RDD_TX_ABS_RECYCLE_COUNTERS_ADDRESS_ARR */
uint32_t RDD_TX_ABS_RECYCLE_COUNTERS_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2e28,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TX_ABS_RECYCLE_COUNTERS_ADDRESS_ARR */


/* >>>RDD_CPU_RX_COPY_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RX_COPY_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2e30,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_COPY_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_SPDSVC_GEN_PARAMS_TABLE_ADDRESS_ARR */
uint32_t RDD_SPDSVC_GEN_PARAMS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2e40,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SPDSVC_GEN_PARAMS_TABLE_ADDRESS_ARR */


/* >>>RDD_WAN_LOOPBACK_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_WAN_LOOPBACK_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2e70,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_WAN_LOOPBACK_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_INTERRUPT_SCRATCH_ADDRESS_ARR */
uint32_t RDD_CPU_RX_INTERRUPT_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2e7c,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_INTERRUPT_SCRATCH_ADDRESS_ARR */


/* >>>RDD_CPU_VPORT_TO_METER_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_VPORT_TO_METER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2e80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_VPORT_TO_METER_TABLE_ADDRESS_ARR */


/* >>>RDD_SPDSVC_GEN_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_SPDSVC_GEN_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2eb0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SPDSVC_GEN_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_FEED_RING_INTERRUPT_THRESHOLD_ADDRESS_ARR */
uint32_t RDD_CPU_FEED_RING_INTERRUPT_THRESHOLD_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2ee6,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_FEED_RING_INTERRUPT_THRESHOLD_ADDRESS_ARR */


/* >>>RDD_TCPSPDTEST_ENGINE_CONN_INFO_TABLE_ADDRESS_ARR */
uint32_t RDD_TCPSPDTEST_ENGINE_CONN_INFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2ee8,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TCPSPDTEST_ENGINE_CONN_INFO_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_FEED_RING_INTERRUPT_COUNTER_ADDRESS_ARR */
uint32_t RDD_CPU_FEED_RING_INTERRUPT_COUNTER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2f22,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_FEED_RING_INTERRUPT_COUNTER_ADDRESS_ARR */


/* >>>RDD_MAC_TYPE_ADDRESS_ARR */
uint32_t RDD_MAC_TYPE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2f3f,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_MAC_TYPE_ADDRESS_ARR */


/* >>>RDD_CPU_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2f70,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_INTERRUPT_COALESCING_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_LOCAL_SCRATCH_ADDRESS_ARR */
uint32_t RDD_CPU_RX_LOCAL_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2fe0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_LOCAL_SCRATCH_ADDRESS_ARR */


/* >>>RDD_CPU_RING_DESCRIPTORS_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RING_DESCRIPTORS_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3000,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RING_DESCRIPTORS_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_COPY_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_CPU_RX_COPY_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3100,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_COPY_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_RX_COPY_LOCAL_SCRATCH_ADDRESS_ARR */
uint32_t RDD_CPU_RX_COPY_LOCAL_SCRATCH_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3120,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_RX_COPY_LOCAL_SCRATCH_ADDRESS_ARR */


/* >>>RDD_TX_ABS_RECYCLE_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_TX_ABS_RECYCLE_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3140,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TX_ABS_RECYCLE_UPDATE_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3180,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_TX_ABS_RECYCLE_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_TX_ABS_RECYCLE_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x31c0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TX_ABS_RECYCLE_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_CPU_REASON_TO_TC_ADDRESS_ARR */
uint32_t RDD_CPU_REASON_TO_TC_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3220,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_CPU_REASON_TO_TC_ADDRESS_ARR */


/* >>>RDD_TC_TO_CPU_RXQ_ADDRESS_ARR */
uint32_t RDD_TC_TO_CPU_RXQ_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3260,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_TC_TO_CPU_RXQ_ADDRESS_ARR */


/* >>>RDD_EXC_TC_TO_CPU_RXQ_ADDRESS_ARR */
uint32_t RDD_EXC_TC_TO_CPU_RXQ_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x32a0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_EXC_TC_TO_CPU_RXQ_ADDRESS_ARR */


/* >>>RDD_VPORT_TO_CPU_OBJ_ADDRESS_ARR */
uint32_t RDD_VPORT_TO_CPU_OBJ_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x3300,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_VPORT_TO_CPU_OBJ_ADDRESS_ARR */


/* >>>RDD_DHD_RX_COMPLETE_FLOW_RING_BUFFER_ADDRESS_ARR */
uint32_t RDD_DHD_RX_COMPLETE_FLOW_RING_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xa80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_RX_COMPLETE_FLOW_RING_BUFFER_ADDRESS_ARR */


/* >>>RDD_DHD_RX_POST_FLOW_RING_BUFFER_ADDRESS_ARR */
uint32_t RDD_DHD_RX_POST_FLOW_RING_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xb80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_RX_POST_FLOW_RING_BUFFER_ADDRESS_ARR */


/* >>>RDD_DHD_TX_COMPLETE_FLOW_RING_BUFFER_ADDRESS_ARR */
uint32_t RDD_DHD_TX_COMPLETE_FLOW_RING_BUFFER_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xe40,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_TX_COMPLETE_FLOW_RING_BUFFER_ADDRESS_ARR */


/* >>>RDD_DHD_RX_COMPLETE_0_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_RX_COMPLETE_0_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xed0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_RX_COMPLETE_0_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_RX_COMPLETE_1_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_RX_COMPLETE_1_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xee0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_RX_COMPLETE_1_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_RX_COMPLETE_2_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_RX_COMPLETE_2_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xef0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_RX_COMPLETE_2_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_TX_COMPLETE_0_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_TX_COMPLETE_0_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xfd0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_TX_COMPLETE_0_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_RX_POST_RING_SIZE_ADDRESS_ARR */
uint32_t RDD_DHD_RX_POST_RING_SIZE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xfde,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_RX_POST_RING_SIZE_ADDRESS_ARR */


/* >>>RDD_DHD_TX_COMPLETE_1_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_TX_COMPLETE_1_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xfe0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_TX_COMPLETE_1_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_RX_COMPLETE_RING_SIZE_ADDRESS_ARR */
uint32_t RDD_DHD_RX_COMPLETE_RING_SIZE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xfec,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_RX_COMPLETE_RING_SIZE_ADDRESS_ARR */


/* >>>RDD_DHD_TX_COMPLETE_RING_SIZE_ADDRESS_ARR */
uint32_t RDD_DHD_TX_COMPLETE_RING_SIZE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xfee,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_TX_COMPLETE_RING_SIZE_ADDRESS_ARR */


/* >>>RDD_DHD_TX_COMPLETE_2_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_DHD_TX_COMPLETE_2_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xff0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_TX_COMPLETE_2_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_DHD_COMPLETE_COMMON_RADIO_DATA_ADDRESS_ARR */
uint32_t RDD_DHD_COMPLETE_COMMON_RADIO_DATA_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2400,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_COMPLETE_COMMON_RADIO_DATA_ADDRESS_ARR */


/* >>>RDD_DHD_DOORBELL_TX_COMPLETE_VALUE_ADDRESS_ARR */
uint32_t RDD_DHD_DOORBELL_TX_COMPLETE_VALUE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2550,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_DOORBELL_TX_COMPLETE_VALUE_ADDRESS_ARR */


/* >>>RDD_DHD_DOORBELL_RX_COMPLETE_VALUE_ADDRESS_ARR */
uint32_t RDD_DHD_DOORBELL_RX_COMPLETE_VALUE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x25e0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_DOORBELL_RX_COMPLETE_VALUE_ADDRESS_ARR */


/* >>>RDD_DHD_DOORBELL_RX_POST_VALUE_ADDRESS_ARR */
uint32_t RDD_DHD_DOORBELL_RX_POST_VALUE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x25f0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_DOORBELL_RX_POST_VALUE_ADDRESS_ARR */


/* >>>RDD_DHD_FPM_REPLY_ADDRESS_ARR */
uint32_t RDD_DHD_FPM_REPLY_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x28c0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_DHD_FPM_REPLY_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_RATE_LIMITER_TABLE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_RATE_LIMITER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_RATE_LIMITER_TABLE_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_PD_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_PD_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x800,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_PD_FIFO_TABLE_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0xf00,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_SCHEDULING_QUEUE_TABLE_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_COMPLEX_SCHEDULER_TABLE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_COMPLEX_SCHEDULER_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x26c0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_COMPLEX_SCHEDULER_TABLE_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_RATE_LIMITER_VALID_TABLE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_RATE_LIMITER_VALID_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2a20,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_RATE_LIMITER_VALID_TABLE_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2a70,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_DISPATCHER_CREDIT_TABLE_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_BUDGET_ALLOCATION_TIMER_VALUE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_BUDGET_ALLOCATION_TIMER_VALUE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2aa2,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_BUDGET_ALLOCATION_TIMER_VALUE_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_FIRST_QUEUE_MAPPING_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_FIRST_QUEUE_MAPPING_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2aff,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_FIRST_QUEUE_MAPPING_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_TM_ACTION_PTR_TABLE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_TM_ACTION_PTR_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2bc0,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_TM_ACTION_PTR_TABLE_ADDRESS_ARR */


/* >>>RDD_SERVICE_QUEUES_UPDATE_FIFO_TABLE_ADDRESS_ARR */
uint32_t RDD_SERVICE_QUEUES_UPDATE_FIFO_TABLE_ADDRESS_ARR[GROUPED_EN_SEGMENTS_NUM] = {
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
	0x2f80,
	INVALID_TABLE_ADDRESS,
	INVALID_TABLE_ADDRESS,
};
/* <<<RDD_SERVICE_QUEUES_UPDATE_FIFO_TABLE_ADDRESS_ARR */

