dynamic: install


all: install


install:
	cp -f nvram_94908HND.save $(INSTALL_DIR)/bin/nvram
	cp -f libnvram.so_94908HND.save $(INSTALL_DIR)/lib/libnvram.so
	cp -f nvram_params_94908HND.save $(INSTALL_DIR)/etc/wlan/nvram_params
