#ifndef IMAGE_3_CODE_ADDRESSES
#define IMAGE_3_CODE_ADDRESSES

#define image_3_start_task_initialization_task		(0x18)
#define image_3_initialization_task		(0x18)
#define image_3_start_task_update_fifo_read_1st_wakeup_request		(0x10B4)
#define image_3_update_fifo_read_1st_wakeup_request		(0x10B4)
#define image_3_start_task_tx_task_1st_wakeup_request		(0x17C)
#define image_3_tx_task_1st_wakeup_request		(0x17C)
#define image_3_start_task_epon_update_fifo_read_1st_wakeup_request		(0x134C)
#define image_3_epon_update_fifo_read_1st_wakeup_request		(0x134C)
#define image_3_start_task_epon_tx_task_wakeup_request		(0x67C)
#define image_3_epon_tx_task_wakeup_request		(0x67C)
#define image_3_start_task_flush_task_1st_wakeup_request		(0x950)
#define image_3_flush_task_1st_wakeup_request		(0x950)
#define image_3_start_task_budget_allocator_1st_wakeup_request		(0xA4C)
#define image_3_budget_allocator_1st_wakeup_request		(0xA4C)
#define image_3_start_task_debug_routine		(0x90)
#define image_3_debug_routine		(0x90)
#define image_3_start_task_ovl_budget_allocator_1st_wakeup_request		(0xD2C)
#define image_3_ovl_budget_allocator_1st_wakeup_request		(0xD2C)
#define image_3_debug_routine_handler		(0xC)
#define image_3_scheduling_update_status		(0x538)
#define image_3_scheduling_action_not_valid		(0x61C)
#define image_3_basic_scheduler_update_dwrr		(0x80C)
#define image_3_complex_scheduler_update_dwrr_basic_schedulers		(0x91C)
#define image_3_complex_scheduler_update_dwrr_queues		(0x92C)
#define image_3_basic_rate_limiter_complex_scheduler		(0xE00)
#define image_3_basic_rate_limiter_basic_scheduler_no_cs		(0xE38)
#define image_3_basic_rate_limiter_queue_with_cs_bs		(0xE6C)
#define image_3_basic_rate_limiter_queue_with_bs		(0xEC0)
#define image_3_ovl_rate_limiter		(0xEFC)
#define image_3_complex_rate_limiter_queue_sir		(0xF10)
#define image_3_complex_rate_limiter_queue_pir		(0xF4C)
#define image_3_complex_rate_limiter_basic_scheduler_sir		(0xF88)
#define image_3_complex_rate_limiter_basic_scheduler_pir		(0xFC4)

#endif
