#ifndef IMAGE_0_CODE_ADDRESSES
#define IMAGE_0_CODE_ADDRESSES

#define image_0_start_task_initialization_task		(0x18)
#define image_0_initialization_task		(0x18)
#define image_0_start_task_update_fifo_read_1st_wakeup_request		(0x90C)
#define image_0_update_fifo_read_1st_wakeup_request		(0x90C)
#define image_0_start_task_tx_task_1st_wakeup_request		(0xE88)
#define image_0_tx_task_1st_wakeup_request		(0xE88)
#define image_0_tx_task_wakeup_request		(0xE88)
#define image_0_start_task_g9991_tx_task_1st_wakeup_request		(0xBAC)
#define image_0_g9991_tx_task_1st_wakeup_request		(0xBAC)
#define image_0_start_task_flush_task_1st_wakeup_request		(0x280)
#define image_0_flush_task_1st_wakeup_request		(0x280)
#define image_0_start_task_budget_allocator_1st_wakeup_request		(0x398)
#define image_0_budget_allocator_1st_wakeup_request		(0x398)
#define image_0_start_task_g9991_flow_control_wakeup_request		(0xDB4)
#define image_0_g9991_flow_control_wakeup_request		(0xDB4)
#define image_0_start_task_debug_routine		(0x90)
#define image_0_debug_routine		(0x90)
#define image_0_start_task_g9991_system_port_wakeup_request		(0x140C)
#define image_0_g9991_system_port_wakeup_request		(0x140C)
#define image_0_debug_routine_handler		(0xC)
#define image_0_complex_scheduler_update_dwrr_basic_schedulers		(0x260)
#define image_0_complex_scheduler_update_dwrr_queues		(0x270)
#define image_0_basic_rate_limiter_complex_scheduler		(0x674)
#define image_0_basic_rate_limiter_basic_scheduler_no_cs		(0x6AC)
#define image_0_basic_rate_limiter_queue_with_cs_bs		(0x6E0)
#define image_0_basic_rate_limiter_queue_with_bs		(0x734)
#define image_0_complex_rate_limiter_queue_sir		(0x770)
#define image_0_complex_rate_limiter_queue_pir		(0x7AC)
#define image_0_complex_rate_limiter_basic_scheduler_sir		(0x7E8)
#define image_0_complex_rate_limiter_basic_scheduler_pir		(0x824)
#define image_0_basic_scheduler_update_dwrr		(0x8FC)
#define image_0_scheduling_update_status		(0x11E4)
#define image_0_scheduling_action_not_valid		(0x1300)

#endif
