#ifndef IMAGE_0_CODE_ADDRESSES
#define IMAGE_0_CODE_ADDRESSES

#define image_0_start_task_initialization_task		(0x58)
#define image_0_initialization_task		(0x58)
#define image_0_start_task_update_fifo_read_1st_wakeup_request		(0x1084)
#define image_0_update_fifo_read_1st_wakeup_request		(0x1084)
#define image_0_start_task_ghost_reporting_1st_wakeup_request		(0xD2C)
#define image_0_ghost_reporting_1st_wakeup_request		(0xD2C)
#define image_0_start_task_budget_allocator_1st_wakeup_request		(0x5EC)
#define image_0_budget_allocator_1st_wakeup_request		(0x5EC)
#define image_0_start_task_debug_routine		(0x90)
#define image_0_debug_routine		(0x90)
#define image_0_start_task_ds_tx_task_wakeup_request		(0x17C)
#define image_0_ds_tx_task_wakeup_request		(0x17C)
#define image_0_start_task_flush_task_1st_wakeup_request		(0xC14)
#define image_0_flush_task_1st_wakeup_request		(0xC14)
#define image_0_debug_routine_handler		(0xC)
#define image_0_ds_tx_scheduling_update_status		(0x410)
#define image_0_ds_tx_scheduling_action_not_valid		(0x49C)
#define image_0_complex_scheduler_update_dwrr_basic_schedulers		(0x5CC)
#define image_0_complex_scheduler_update_dwrr_queues		(0x5DC)
#define image_0_basic_rate_limiter_complex_scheduler		(0x8C8)
#define image_0_basic_rate_limiter_basic_scheduler_no_cs		(0x900)
#define image_0_basic_rate_limiter_queue_with_cs_bs		(0x934)
#define image_0_basic_rate_limiter_queue_with_bs		(0x988)
#define image_0_complex_rate_limiter_queue_sir		(0x9C4)
#define image_0_complex_rate_limiter_queue_pir		(0xA00)
#define image_0_complex_rate_limiter_basic_scheduler_sir		(0xA3C)
#define image_0_complex_rate_limiter_basic_scheduler_pir		(0xA78)
#define image_0_basic_scheduler_update_dwrr		(0xB50)

#endif
