#ifndef IMAGE_3_CODE_ADDRESSES
#define IMAGE_3_CODE_ADDRESSES

#define image_3_start_task_initialization_task		(0x18)
#define image_3_initialization_task		(0x18)
#define image_3_start_task_update_fifo_read_1st_wakeup_request		(0x25F8)
#define image_3_update_fifo_read_1st_wakeup_request		(0x25F8)
#define image_3_start_task_tx_task_1st_wakeup_request		(0x13C)
#define image_3_tx_task_1st_wakeup_request		(0x13C)
#define image_3_start_task_epon_update_fifo_read_1st_wakeup_request		(0x2890)
#define image_3_epon_update_fifo_read_1st_wakeup_request		(0x2890)
#define image_3_start_task_epon_tx_task_wakeup_request		(0x63C)
#define image_3_epon_tx_task_wakeup_request		(0x63C)
#define image_3_start_task_budget_allocator_1st_wakeup_request		(0x90C)
#define image_3_budget_allocator_1st_wakeup_request		(0x90C)
#define image_3_start_task_debug_routine		(0x50)
#define image_3_debug_routine		(0x50)
#define image_3_start_task_ovl_budget_allocator_1st_wakeup_request		(0xBEC)
#define image_3_ovl_budget_allocator_1st_wakeup_request		(0xBEC)
#define image_3_start_task_flush_task_1st_wakeup_request		(0xF74)
#define image_3_flush_task_1st_wakeup_request		(0xF74)
#define image_3_start_task_dhd_tx_post_wakeup_request		(0x14E0)
#define image_3_dhd_tx_post_wakeup_request		(0x14E0)
#define image_3_start_task_dhd_tx_post_update_fifo_wakeup_request		(0x1488)
#define image_3_dhd_tx_post_update_fifo_wakeup_request		(0x1488)
#define image_3_start_task_dhd_timer_1st_wakeup_request		(0x10B0)
#define image_3_dhd_timer_1st_wakeup_request		(0x10B0)
#define image_3_start_task_dhd_mcast_wakeup_request		(0x2058)
#define image_3_dhd_mcast_wakeup_request		(0x2058)
#define image_3_start_task_dhd_mcast_update_fifo_wakeup_request		(0x2020)
#define image_3_dhd_mcast_update_fifo_wakeup_request		(0x2020)
#define image_3_debug_routine_handler		(0xC)
#define image_3_scheduling_update_status		(0x4F8)
#define image_3_scheduling_action_not_valid		(0x5DC)
#define image_3_basic_scheduler_update_dwrr		(0x7C8)
#define image_3_complex_scheduler_update_dwrr_basic_schedulers		(0x8D8)
#define image_3_complex_scheduler_update_dwrr_queues		(0x8E8)
#define image_3_basic_rate_limiter_complex_scheduler		(0xCC0)
#define image_3_basic_rate_limiter_basic_scheduler_no_cs		(0xCF8)
#define image_3_basic_rate_limiter_queue_with_cs_bs		(0xD2C)
#define image_3_basic_rate_limiter_queue_with_bs		(0xD80)
#define image_3_ovl_rate_limiter		(0xDBC)
#define image_3_complex_rate_limiter_queue_sir		(0xDD0)
#define image_3_complex_rate_limiter_queue_pir		(0xE0C)
#define image_3_complex_rate_limiter_basic_scheduler_sir		(0xE48)
#define image_3_complex_rate_limiter_basic_scheduler_pir		(0xE84)

#endif
